package com.nwafu.databaseoprations.entity;

import java.io.Serializable;

public class FarmInfomation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm_infomation.farmUuid
     *
     * @mbg.generated
     */
    private String farmUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm_infomation.farmName
     *
     * @mbg.generated
     */
    private String farmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm_infomation.ownUser
     *
     * @mbg.generated
     */
    private String ownUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm_infomation.farmAddress
     *
     * @mbg.generated
     */
    private String farmAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table farm_infomation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm_infomation.farmUuid
     *
     * @return the value of farm_infomation.farmUuid
     *
     * @mbg.generated
     */
    public String getFarmUuid() {
        return farmUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm_infomation.farmUuid
     *
     * @param farmUuid the value for farm_infomation.farmUuid
     *
     * @mbg.generated
     */
    public void setFarmUuid(String farmUuid) {
        this.farmUuid = farmUuid == null ? null : farmUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm_infomation.farmName
     *
     * @return the value of farm_infomation.farmName
     *
     * @mbg.generated
     */
    public String getFarmName() {
        return farmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm_infomation.farmName
     *
     * @param farmName the value for farm_infomation.farmName
     *
     * @mbg.generated
     */
    public void setFarmName(String farmName) {
        this.farmName = farmName == null ? null : farmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm_infomation.ownUser
     *
     * @return the value of farm_infomation.ownUser
     *
     * @mbg.generated
     */
    public String getOwnUser() {
        return ownUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm_infomation.ownUser
     *
     * @param ownUser the value for farm_infomation.ownUser
     *
     * @mbg.generated
     */
    public void setOwnUser(String ownUser) {
        this.ownUser = ownUser == null ? null : ownUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm_infomation.farmAddress
     *
     * @return the value of farm_infomation.farmAddress
     *
     * @mbg.generated
     */
    public String getFarmAddress() {
        return farmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm_infomation.farmAddress
     *
     * @param farmAddress the value for farm_infomation.farmAddress
     *
     * @mbg.generated
     */
    public void setFarmAddress(String farmAddress) {
        this.farmAddress = farmAddress == null ? null : farmAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_infomation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", farmUuid=").append(farmUuid);
        sb.append(", farmName=").append(farmName);
        sb.append(", ownUser=").append(ownUser);
        sb.append(", farmAddress=").append(farmAddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}