package com.nwafu.databaseoprations.entity;

import java.io.Serializable;

public class RabbitDynamicInformation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.dynamicInformationId
     *
     * @mbg.generated
     */
    private Integer dynamicInformationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.rabbitNo
     *
     * @mbg.generated
     */
    private String rabbitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.weight
     *
     * @mbg.generated
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.bodyLength
     *
     * @mbg.generated
     */
    private Double bodyLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.bust
     *
     * @mbg.generated
     */
    private Double bust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.backRoughLength
     *
     * @mbg.generated
     */
    private Double backRoughLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.bodySideHairLength
     *
     * @mbg.generated
     */
    private Double bodySideHairLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.abdominalThickHairLength
     *
     * @mbg.generated
     */
    private Double abdominalThickHairLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.hipRoughLength
     *
     * @mbg.generated
     */
    private Double hipRoughLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.longBackHairLength
     *
     * @mbg.generated
     */
    private Double longBackHairLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.bellyHairLength
     *
     * @mbg.generated
     */
    private Double bellyHairLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.hipVelvetLength
     *
     * @mbg.generated
     */
    private Double hipVelvetLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.longSideHairsLength
     *
     * @mbg.generated
     */
    private Double longSideHairsLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.backCrudeHairDensity
     *
     * @mbg.generated
     */
    private Double backCrudeHairDensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.abdominalCrudeHairDensity
     *
     * @mbg.generated
     */
    private Double abdominalCrudeHairDensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.hipCrudeHairDensity
     *
     * @mbg.generated
     */
    private Double hipCrudeHairDensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.thickSideHairDensity
     *
     * @mbg.generated
     */
    private Double thickSideHairDensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.backFineHairDensity
     *
     * @mbg.generated
     */
    private Double backFineHairDensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.abdominalFineHairDensity
     *
     * @mbg.generated
     */
    private Double abdominalFineHairDensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.hipFineHairDensity
     *
     * @mbg.generated
     */
    private Double hipFineHairDensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.bodySideFineHairDensity
     *
     * @mbg.generated
     */
    private Double bodySideFineHairDensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.backHairFineness
     *
     * @mbg.generated
     */
    private Double backHairFineness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.abdominalCapillary
     *
     * @mbg.generated
     */
    private Double abdominalCapillary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.hipHairFineness
     *
     * @mbg.generated
     */
    private Double hipHairFineness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.bodyDideCapillary
     *
     * @mbg.generated
     */
    private Double bodyDideCapillary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.roughnessRate
     *
     * @mbg.generated
     */
    private Double roughnessRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.singleHairProduction
     *
     * @mbg.generated
     */
    private Double singleHairProduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.estimateAnnualShear
     *
     * @mbg.generated
     */
    private Double estimateAnnualShear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.loosenessRate
     *
     * @mbg.generated
     */
    private Double loosenessRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.strong
     *
     * @mbg.generated
     */
    private Double strong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.elongation
     *
     * @mbg.generated
     */
    private Double elongation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.hairFlatness
     *
     * @mbg.generated
     */
    private Double hairFlatness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.coatElasticity
     *
     * @mbg.generated
     */
    private Double coatElasticity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.coatAdhesion
     *
     * @mbg.generated
     */
    private Double coatAdhesion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_dynamic_information.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rabbit_dynamic_information
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.dynamicInformationId
     *
     * @return the value of rabbit_dynamic_information.dynamicInformationId
     *
     * @mbg.generated
     */
    public Integer getDynamicInformationId() {
        return dynamicInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.dynamicInformationId
     *
     * @param dynamicInformationId the value for rabbit_dynamic_information.dynamicInformationId
     *
     * @mbg.generated
     */
    public void setDynamicInformationId(Integer dynamicInformationId) {
        this.dynamicInformationId = dynamicInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.rabbitNo
     *
     * @return the value of rabbit_dynamic_information.rabbitNo
     *
     * @mbg.generated
     */
    public String getRabbitNo() {
        return rabbitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.rabbitNo
     *
     * @param rabbitNo the value for rabbit_dynamic_information.rabbitNo
     *
     * @mbg.generated
     */
    public void setRabbitNo(String rabbitNo) {
        this.rabbitNo = rabbitNo == null ? null : rabbitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.weight
     *
     * @return the value of rabbit_dynamic_information.weight
     *
     * @mbg.generated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.weight
     *
     * @param weight the value for rabbit_dynamic_information.weight
     *
     * @mbg.generated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.bodyLength
     *
     * @return the value of rabbit_dynamic_information.bodyLength
     *
     * @mbg.generated
     */
    public Double getBodyLength() {
        return bodyLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.bodyLength
     *
     * @param bodyLength the value for rabbit_dynamic_information.bodyLength
     *
     * @mbg.generated
     */
    public void setBodyLength(Double bodyLength) {
        this.bodyLength = bodyLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.bust
     *
     * @return the value of rabbit_dynamic_information.bust
     *
     * @mbg.generated
     */
    public Double getBust() {
        return bust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.bust
     *
     * @param bust the value for rabbit_dynamic_information.bust
     *
     * @mbg.generated
     */
    public void setBust(Double bust) {
        this.bust = bust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.backRoughLength
     *
     * @return the value of rabbit_dynamic_information.backRoughLength
     *
     * @mbg.generated
     */
    public Double getBackRoughLength() {
        return backRoughLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.backRoughLength
     *
     * @param backRoughLength the value for rabbit_dynamic_information.backRoughLength
     *
     * @mbg.generated
     */
    public void setBackRoughLength(Double backRoughLength) {
        this.backRoughLength = backRoughLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.bodySideHairLength
     *
     * @return the value of rabbit_dynamic_information.bodySideHairLength
     *
     * @mbg.generated
     */
    public Double getBodySideHairLength() {
        return bodySideHairLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.bodySideHairLength
     *
     * @param bodySideHairLength the value for rabbit_dynamic_information.bodySideHairLength
     *
     * @mbg.generated
     */
    public void setBodySideHairLength(Double bodySideHairLength) {
        this.bodySideHairLength = bodySideHairLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.abdominalThickHairLength
     *
     * @return the value of rabbit_dynamic_information.abdominalThickHairLength
     *
     * @mbg.generated
     */
    public Double getAbdominalThickHairLength() {
        return abdominalThickHairLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.abdominalThickHairLength
     *
     * @param abdominalThickHairLength the value for rabbit_dynamic_information.abdominalThickHairLength
     *
     * @mbg.generated
     */
    public void setAbdominalThickHairLength(Double abdominalThickHairLength) {
        this.abdominalThickHairLength = abdominalThickHairLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.hipRoughLength
     *
     * @return the value of rabbit_dynamic_information.hipRoughLength
     *
     * @mbg.generated
     */
    public Double getHipRoughLength() {
        return hipRoughLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.hipRoughLength
     *
     * @param hipRoughLength the value for rabbit_dynamic_information.hipRoughLength
     *
     * @mbg.generated
     */
    public void setHipRoughLength(Double hipRoughLength) {
        this.hipRoughLength = hipRoughLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.longBackHairLength
     *
     * @return the value of rabbit_dynamic_information.longBackHairLength
     *
     * @mbg.generated
     */
    public Double getLongBackHairLength() {
        return longBackHairLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.longBackHairLength
     *
     * @param longBackHairLength the value for rabbit_dynamic_information.longBackHairLength
     *
     * @mbg.generated
     */
    public void setLongBackHairLength(Double longBackHairLength) {
        this.longBackHairLength = longBackHairLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.bellyHairLength
     *
     * @return the value of rabbit_dynamic_information.bellyHairLength
     *
     * @mbg.generated
     */
    public Double getBellyHairLength() {
        return bellyHairLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.bellyHairLength
     *
     * @param bellyHairLength the value for rabbit_dynamic_information.bellyHairLength
     *
     * @mbg.generated
     */
    public void setBellyHairLength(Double bellyHairLength) {
        this.bellyHairLength = bellyHairLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.hipVelvetLength
     *
     * @return the value of rabbit_dynamic_information.hipVelvetLength
     *
     * @mbg.generated
     */
    public Double getHipVelvetLength() {
        return hipVelvetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.hipVelvetLength
     *
     * @param hipVelvetLength the value for rabbit_dynamic_information.hipVelvetLength
     *
     * @mbg.generated
     */
    public void setHipVelvetLength(Double hipVelvetLength) {
        this.hipVelvetLength = hipVelvetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.longSideHairsLength
     *
     * @return the value of rabbit_dynamic_information.longSideHairsLength
     *
     * @mbg.generated
     */
    public Double getLongSideHairsLength() {
        return longSideHairsLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.longSideHairsLength
     *
     * @param longSideHairsLength the value for rabbit_dynamic_information.longSideHairsLength
     *
     * @mbg.generated
     */
    public void setLongSideHairsLength(Double longSideHairsLength) {
        this.longSideHairsLength = longSideHairsLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.backCrudeHairDensity
     *
     * @return the value of rabbit_dynamic_information.backCrudeHairDensity
     *
     * @mbg.generated
     */
    public Double getBackCrudeHairDensity() {
        return backCrudeHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.backCrudeHairDensity
     *
     * @param backCrudeHairDensity the value for rabbit_dynamic_information.backCrudeHairDensity
     *
     * @mbg.generated
     */
    public void setBackCrudeHairDensity(Double backCrudeHairDensity) {
        this.backCrudeHairDensity = backCrudeHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.abdominalCrudeHairDensity
     *
     * @return the value of rabbit_dynamic_information.abdominalCrudeHairDensity
     *
     * @mbg.generated
     */
    public Double getAbdominalCrudeHairDensity() {
        return abdominalCrudeHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.abdominalCrudeHairDensity
     *
     * @param abdominalCrudeHairDensity the value for rabbit_dynamic_information.abdominalCrudeHairDensity
     *
     * @mbg.generated
     */
    public void setAbdominalCrudeHairDensity(Double abdominalCrudeHairDensity) {
        this.abdominalCrudeHairDensity = abdominalCrudeHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.hipCrudeHairDensity
     *
     * @return the value of rabbit_dynamic_information.hipCrudeHairDensity
     *
     * @mbg.generated
     */
    public Double getHipCrudeHairDensity() {
        return hipCrudeHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.hipCrudeHairDensity
     *
     * @param hipCrudeHairDensity the value for rabbit_dynamic_information.hipCrudeHairDensity
     *
     * @mbg.generated
     */
    public void setHipCrudeHairDensity(Double hipCrudeHairDensity) {
        this.hipCrudeHairDensity = hipCrudeHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.thickSideHairDensity
     *
     * @return the value of rabbit_dynamic_information.thickSideHairDensity
     *
     * @mbg.generated
     */
    public Double getThickSideHairDensity() {
        return thickSideHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.thickSideHairDensity
     *
     * @param thickSideHairDensity the value for rabbit_dynamic_information.thickSideHairDensity
     *
     * @mbg.generated
     */
    public void setThickSideHairDensity(Double thickSideHairDensity) {
        this.thickSideHairDensity = thickSideHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.backFineHairDensity
     *
     * @return the value of rabbit_dynamic_information.backFineHairDensity
     *
     * @mbg.generated
     */
    public Double getBackFineHairDensity() {
        return backFineHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.backFineHairDensity
     *
     * @param backFineHairDensity the value for rabbit_dynamic_information.backFineHairDensity
     *
     * @mbg.generated
     */
    public void setBackFineHairDensity(Double backFineHairDensity) {
        this.backFineHairDensity = backFineHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.abdominalFineHairDensity
     *
     * @return the value of rabbit_dynamic_information.abdominalFineHairDensity
     *
     * @mbg.generated
     */
    public Double getAbdominalFineHairDensity() {
        return abdominalFineHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.abdominalFineHairDensity
     *
     * @param abdominalFineHairDensity the value for rabbit_dynamic_information.abdominalFineHairDensity
     *
     * @mbg.generated
     */
    public void setAbdominalFineHairDensity(Double abdominalFineHairDensity) {
        this.abdominalFineHairDensity = abdominalFineHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.hipFineHairDensity
     *
     * @return the value of rabbit_dynamic_information.hipFineHairDensity
     *
     * @mbg.generated
     */
    public Double getHipFineHairDensity() {
        return hipFineHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.hipFineHairDensity
     *
     * @param hipFineHairDensity the value for rabbit_dynamic_information.hipFineHairDensity
     *
     * @mbg.generated
     */
    public void setHipFineHairDensity(Double hipFineHairDensity) {
        this.hipFineHairDensity = hipFineHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.bodySideFineHairDensity
     *
     * @return the value of rabbit_dynamic_information.bodySideFineHairDensity
     *
     * @mbg.generated
     */
    public Double getBodySideFineHairDensity() {
        return bodySideFineHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.bodySideFineHairDensity
     *
     * @param bodySideFineHairDensity the value for rabbit_dynamic_information.bodySideFineHairDensity
     *
     * @mbg.generated
     */
    public void setBodySideFineHairDensity(Double bodySideFineHairDensity) {
        this.bodySideFineHairDensity = bodySideFineHairDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.backHairFineness
     *
     * @return the value of rabbit_dynamic_information.backHairFineness
     *
     * @mbg.generated
     */
    public Double getBackHairFineness() {
        return backHairFineness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.backHairFineness
     *
     * @param backHairFineness the value for rabbit_dynamic_information.backHairFineness
     *
     * @mbg.generated
     */
    public void setBackHairFineness(Double backHairFineness) {
        this.backHairFineness = backHairFineness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.abdominalCapillary
     *
     * @return the value of rabbit_dynamic_information.abdominalCapillary
     *
     * @mbg.generated
     */
    public Double getAbdominalCapillary() {
        return abdominalCapillary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.abdominalCapillary
     *
     * @param abdominalCapillary the value for rabbit_dynamic_information.abdominalCapillary
     *
     * @mbg.generated
     */
    public void setAbdominalCapillary(Double abdominalCapillary) {
        this.abdominalCapillary = abdominalCapillary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.hipHairFineness
     *
     * @return the value of rabbit_dynamic_information.hipHairFineness
     *
     * @mbg.generated
     */
    public Double getHipHairFineness() {
        return hipHairFineness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.hipHairFineness
     *
     * @param hipHairFineness the value for rabbit_dynamic_information.hipHairFineness
     *
     * @mbg.generated
     */
    public void setHipHairFineness(Double hipHairFineness) {
        this.hipHairFineness = hipHairFineness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.bodyDideCapillary
     *
     * @return the value of rabbit_dynamic_information.bodyDideCapillary
     *
     * @mbg.generated
     */
    public Double getBodyDideCapillary() {
        return bodyDideCapillary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.bodyDideCapillary
     *
     * @param bodyDideCapillary the value for rabbit_dynamic_information.bodyDideCapillary
     *
     * @mbg.generated
     */
    public void setBodyDideCapillary(Double bodyDideCapillary) {
        this.bodyDideCapillary = bodyDideCapillary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.roughnessRate
     *
     * @return the value of rabbit_dynamic_information.roughnessRate
     *
     * @mbg.generated
     */
    public Double getRoughnessRate() {
        return roughnessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.roughnessRate
     *
     * @param roughnessRate the value for rabbit_dynamic_information.roughnessRate
     *
     * @mbg.generated
     */
    public void setRoughnessRate(Double roughnessRate) {
        this.roughnessRate = roughnessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.singleHairProduction
     *
     * @return the value of rabbit_dynamic_information.singleHairProduction
     *
     * @mbg.generated
     */
    public Double getSingleHairProduction() {
        return singleHairProduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.singleHairProduction
     *
     * @param singleHairProduction the value for rabbit_dynamic_information.singleHairProduction
     *
     * @mbg.generated
     */
    public void setSingleHairProduction(Double singleHairProduction) {
        this.singleHairProduction = singleHairProduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.estimateAnnualShear
     *
     * @return the value of rabbit_dynamic_information.estimateAnnualShear
     *
     * @mbg.generated
     */
    public Double getEstimateAnnualShear() {
        return estimateAnnualShear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.estimateAnnualShear
     *
     * @param estimateAnnualShear the value for rabbit_dynamic_information.estimateAnnualShear
     *
     * @mbg.generated
     */
    public void setEstimateAnnualShear(Double estimateAnnualShear) {
        this.estimateAnnualShear = estimateAnnualShear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.loosenessRate
     *
     * @return the value of rabbit_dynamic_information.loosenessRate
     *
     * @mbg.generated
     */
    public Double getLoosenessRate() {
        return loosenessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.loosenessRate
     *
     * @param loosenessRate the value for rabbit_dynamic_information.loosenessRate
     *
     * @mbg.generated
     */
    public void setLoosenessRate(Double loosenessRate) {
        this.loosenessRate = loosenessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.strong
     *
     * @return the value of rabbit_dynamic_information.strong
     *
     * @mbg.generated
     */
    public Double getStrong() {
        return strong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.strong
     *
     * @param strong the value for rabbit_dynamic_information.strong
     *
     * @mbg.generated
     */
    public void setStrong(Double strong) {
        this.strong = strong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.elongation
     *
     * @return the value of rabbit_dynamic_information.elongation
     *
     * @mbg.generated
     */
    public Double getElongation() {
        return elongation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.elongation
     *
     * @param elongation the value for rabbit_dynamic_information.elongation
     *
     * @mbg.generated
     */
    public void setElongation(Double elongation) {
        this.elongation = elongation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.hairFlatness
     *
     * @return the value of rabbit_dynamic_information.hairFlatness
     *
     * @mbg.generated
     */
    public Double getHairFlatness() {
        return hairFlatness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.hairFlatness
     *
     * @param hairFlatness the value for rabbit_dynamic_information.hairFlatness
     *
     * @mbg.generated
     */
    public void setHairFlatness(Double hairFlatness) {
        this.hairFlatness = hairFlatness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.coatElasticity
     *
     * @return the value of rabbit_dynamic_information.coatElasticity
     *
     * @mbg.generated
     */
    public Double getCoatElasticity() {
        return coatElasticity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.coatElasticity
     *
     * @param coatElasticity the value for rabbit_dynamic_information.coatElasticity
     *
     * @mbg.generated
     */
    public void setCoatElasticity(Double coatElasticity) {
        this.coatElasticity = coatElasticity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.coatAdhesion
     *
     * @return the value of rabbit_dynamic_information.coatAdhesion
     *
     * @mbg.generated
     */
    public Double getCoatAdhesion() {
        return coatAdhesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.coatAdhesion
     *
     * @param coatAdhesion the value for rabbit_dynamic_information.coatAdhesion
     *
     * @mbg.generated
     */
    public void setCoatAdhesion(Double coatAdhesion) {
        this.coatAdhesion = coatAdhesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_dynamic_information.period
     *
     * @return the value of rabbit_dynamic_information.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_dynamic_information.period
     *
     * @param period the value for rabbit_dynamic_information.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_dynamic_information
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dynamicInformationId=").append(dynamicInformationId);
        sb.append(", rabbitNo=").append(rabbitNo);
        sb.append(", weight=").append(weight);
        sb.append(", bodyLength=").append(bodyLength);
        sb.append(", bust=").append(bust);
        sb.append(", backRoughLength=").append(backRoughLength);
        sb.append(", bodySideHairLength=").append(bodySideHairLength);
        sb.append(", abdominalThickHairLength=").append(abdominalThickHairLength);
        sb.append(", hipRoughLength=").append(hipRoughLength);
        sb.append(", longBackHairLength=").append(longBackHairLength);
        sb.append(", bellyHairLength=").append(bellyHairLength);
        sb.append(", hipVelvetLength=").append(hipVelvetLength);
        sb.append(", longSideHairsLength=").append(longSideHairsLength);
        sb.append(", backCrudeHairDensity=").append(backCrudeHairDensity);
        sb.append(", abdominalCrudeHairDensity=").append(abdominalCrudeHairDensity);
        sb.append(", hipCrudeHairDensity=").append(hipCrudeHairDensity);
        sb.append(", thickSideHairDensity=").append(thickSideHairDensity);
        sb.append(", backFineHairDensity=").append(backFineHairDensity);
        sb.append(", abdominalFineHairDensity=").append(abdominalFineHairDensity);
        sb.append(", hipFineHairDensity=").append(hipFineHairDensity);
        sb.append(", bodySideFineHairDensity=").append(bodySideFineHairDensity);
        sb.append(", backHairFineness=").append(backHairFineness);
        sb.append(", abdominalCapillary=").append(abdominalCapillary);
        sb.append(", hipHairFineness=").append(hipHairFineness);
        sb.append(", bodyDideCapillary=").append(bodyDideCapillary);
        sb.append(", roughnessRate=").append(roughnessRate);
        sb.append(", singleHairProduction=").append(singleHairProduction);
        sb.append(", estimateAnnualShear=").append(estimateAnnualShear);
        sb.append(", loosenessRate=").append(loosenessRate);
        sb.append(", strong=").append(strong);
        sb.append(", elongation=").append(elongation);
        sb.append(", hairFlatness=").append(hairFlatness);
        sb.append(", coatElasticity=").append(coatElasticity);
        sb.append(", coatAdhesion=").append(coatAdhesion);
        sb.append(", period=").append(period);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}