package com.nwafu.databaseoprations.entity;

import java.io.Serializable;

public class RabbitHouse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.rabbitHouseNo
     *
     * @mbg.generated
     */
    private String rabbitHouseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.outdoorTemperature
     *
     * @mbg.generated
     */
    private Double outdoorTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.outdoorUmidity
     *
     * @mbg.generated
     */
    private Double outdoorUmidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.indoorTemperature
     *
     * @mbg.generated
     */
    private Double indoorTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.indoorUmidity
     *
     * @mbg.generated
     */
    private Double indoorUmidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.indoorWindSpeed
     *
     * @mbg.generated
     */
    private Double indoorWindSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.ammonia
     *
     * @mbg.generated
     */
    private Double ammonia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.hydrogenSulfide
     *
     * @mbg.generated
     */
    private Double hydrogenSulfide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.carbonMonoxideConcentration
     *
     * @mbg.generated
     */
    private Double carbonMonoxideConcentration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.fanOperation
     *
     * @mbg.generated
     */
    private String fanOperation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.wetCurtainOperation
     *
     * @mbg.generated
     */
    private String wetCurtainOperation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_house.lightingControl
     *
     * @mbg.generated
     */
    private String lightingControl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rabbit_house
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.rabbitHouseNo
     *
     * @return the value of rabbit_house.rabbitHouseNo
     *
     * @mbg.generated
     */
    public String getRabbitHouseNo() {
        return rabbitHouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.rabbitHouseNo
     *
     * @param rabbitHouseNo the value for rabbit_house.rabbitHouseNo
     *
     * @mbg.generated
     */
    public void setRabbitHouseNo(String rabbitHouseNo) {
        this.rabbitHouseNo = rabbitHouseNo == null ? null : rabbitHouseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.outdoorTemperature
     *
     * @return the value of rabbit_house.outdoorTemperature
     *
     * @mbg.generated
     */
    public Double getOutdoorTemperature() {
        return outdoorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.outdoorTemperature
     *
     * @param outdoorTemperature the value for rabbit_house.outdoorTemperature
     *
     * @mbg.generated
     */
    public void setOutdoorTemperature(Double outdoorTemperature) {
        this.outdoorTemperature = outdoorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.outdoorUmidity
     *
     * @return the value of rabbit_house.outdoorUmidity
     *
     * @mbg.generated
     */
    public Double getOutdoorUmidity() {
        return outdoorUmidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.outdoorUmidity
     *
     * @param outdoorUmidity the value for rabbit_house.outdoorUmidity
     *
     * @mbg.generated
     */
    public void setOutdoorUmidity(Double outdoorUmidity) {
        this.outdoorUmidity = outdoorUmidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.indoorTemperature
     *
     * @return the value of rabbit_house.indoorTemperature
     *
     * @mbg.generated
     */
    public Double getIndoorTemperature() {
        return indoorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.indoorTemperature
     *
     * @param indoorTemperature the value for rabbit_house.indoorTemperature
     *
     * @mbg.generated
     */
    public void setIndoorTemperature(Double indoorTemperature) {
        this.indoorTemperature = indoorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.indoorUmidity
     *
     * @return the value of rabbit_house.indoorUmidity
     *
     * @mbg.generated
     */
    public Double getIndoorUmidity() {
        return indoorUmidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.indoorUmidity
     *
     * @param indoorUmidity the value for rabbit_house.indoorUmidity
     *
     * @mbg.generated
     */
    public void setIndoorUmidity(Double indoorUmidity) {
        this.indoorUmidity = indoorUmidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.indoorWindSpeed
     *
     * @return the value of rabbit_house.indoorWindSpeed
     *
     * @mbg.generated
     */
    public Double getIndoorWindSpeed() {
        return indoorWindSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.indoorWindSpeed
     *
     * @param indoorWindSpeed the value for rabbit_house.indoorWindSpeed
     *
     * @mbg.generated
     */
    public void setIndoorWindSpeed(Double indoorWindSpeed) {
        this.indoorWindSpeed = indoorWindSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.ammonia
     *
     * @return the value of rabbit_house.ammonia
     *
     * @mbg.generated
     */
    public Double getAmmonia() {
        return ammonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.ammonia
     *
     * @param ammonia the value for rabbit_house.ammonia
     *
     * @mbg.generated
     */
    public void setAmmonia(Double ammonia) {
        this.ammonia = ammonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.hydrogenSulfide
     *
     * @return the value of rabbit_house.hydrogenSulfide
     *
     * @mbg.generated
     */
    public Double getHydrogenSulfide() {
        return hydrogenSulfide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.hydrogenSulfide
     *
     * @param hydrogenSulfide the value for rabbit_house.hydrogenSulfide
     *
     * @mbg.generated
     */
    public void setHydrogenSulfide(Double hydrogenSulfide) {
        this.hydrogenSulfide = hydrogenSulfide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.carbonMonoxideConcentration
     *
     * @return the value of rabbit_house.carbonMonoxideConcentration
     *
     * @mbg.generated
     */
    public Double getCarbonMonoxideConcentration() {
        return carbonMonoxideConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.carbonMonoxideConcentration
     *
     * @param carbonMonoxideConcentration the value for rabbit_house.carbonMonoxideConcentration
     *
     * @mbg.generated
     */
    public void setCarbonMonoxideConcentration(Double carbonMonoxideConcentration) {
        this.carbonMonoxideConcentration = carbonMonoxideConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.fanOperation
     *
     * @return the value of rabbit_house.fanOperation
     *
     * @mbg.generated
     */
    public String getFanOperation() {
        return fanOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.fanOperation
     *
     * @param fanOperation the value for rabbit_house.fanOperation
     *
     * @mbg.generated
     */
    public void setFanOperation(String fanOperation) {
        this.fanOperation = fanOperation == null ? null : fanOperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.wetCurtainOperation
     *
     * @return the value of rabbit_house.wetCurtainOperation
     *
     * @mbg.generated
     */
    public String getWetCurtainOperation() {
        return wetCurtainOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.wetCurtainOperation
     *
     * @param wetCurtainOperation the value for rabbit_house.wetCurtainOperation
     *
     * @mbg.generated
     */
    public void setWetCurtainOperation(String wetCurtainOperation) {
        this.wetCurtainOperation = wetCurtainOperation == null ? null : wetCurtainOperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_house.lightingControl
     *
     * @return the value of rabbit_house.lightingControl
     *
     * @mbg.generated
     */
    public String getLightingControl() {
        return lightingControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_house.lightingControl
     *
     * @param lightingControl the value for rabbit_house.lightingControl
     *
     * @mbg.generated
     */
    public void setLightingControl(String lightingControl) {
        this.lightingControl = lightingControl == null ? null : lightingControl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_house
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rabbitHouseNo=").append(rabbitHouseNo);
        sb.append(", outdoorTemperature=").append(outdoorTemperature);
        sb.append(", outdoorUmidity=").append(outdoorUmidity);
        sb.append(", indoorTemperature=").append(indoorTemperature);
        sb.append(", indoorUmidity=").append(indoorUmidity);
        sb.append(", indoorWindSpeed=").append(indoorWindSpeed);
        sb.append(", ammonia=").append(ammonia);
        sb.append(", hydrogenSulfide=").append(hydrogenSulfide);
        sb.append(", carbonMonoxideConcentration=").append(carbonMonoxideConcentration);
        sb.append(", fanOperation=").append(fanOperation);
        sb.append(", wetCurtainOperation=").append(wetCurtainOperation);
        sb.append(", lightingControl=").append(lightingControl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}