package com.nwafu.databaseoprations.entity;

import java.io.Serializable;
import java.util.Date;

public class RabbitChangeRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.recordId
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.rabbitNo
     *
     * @mbg.generated
     */
    private String rabbitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.oldCageNo
     *
     * @mbg.generated
     */
    private String oldCageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.oldRabbitHouseNo
     *
     * @mbg.generated
     */
    private String oldRabbitHouseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.newCageNo
     *
     * @mbg.generated
     */
    private String newCageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.newRabbitHouseNo
     *
     * @mbg.generated
     */
    private String newRabbitHouseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.actionUser
     *
     * @mbg.generated
     */
    private String actionUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_change_record.changeDate
     *
     * @mbg.generated
     */
    private Date changeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rabbit_change_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.recordId
     *
     * @return the value of rabbit_change_record.recordId
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.recordId
     *
     * @param recordId the value for rabbit_change_record.recordId
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.rabbitNo
     *
     * @return the value of rabbit_change_record.rabbitNo
     *
     * @mbg.generated
     */
    public String getRabbitNo() {
        return rabbitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.rabbitNo
     *
     * @param rabbitNo the value for rabbit_change_record.rabbitNo
     *
     * @mbg.generated
     */
    public void setRabbitNo(String rabbitNo) {
        this.rabbitNo = rabbitNo == null ? null : rabbitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.sex
     *
     * @return the value of rabbit_change_record.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.sex
     *
     * @param sex the value for rabbit_change_record.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.oldCageNo
     *
     * @return the value of rabbit_change_record.oldCageNo
     *
     * @mbg.generated
     */
    public String getOldCageNo() {
        return oldCageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.oldCageNo
     *
     * @param oldCageNo the value for rabbit_change_record.oldCageNo
     *
     * @mbg.generated
     */
    public void setOldCageNo(String oldCageNo) {
        this.oldCageNo = oldCageNo == null ? null : oldCageNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.oldRabbitHouseNo
     *
     * @return the value of rabbit_change_record.oldRabbitHouseNo
     *
     * @mbg.generated
     */
    public String getOldRabbitHouseNo() {
        return oldRabbitHouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.oldRabbitHouseNo
     *
     * @param oldRabbitHouseNo the value for rabbit_change_record.oldRabbitHouseNo
     *
     * @mbg.generated
     */
    public void setOldRabbitHouseNo(String oldRabbitHouseNo) {
        this.oldRabbitHouseNo = oldRabbitHouseNo == null ? null : oldRabbitHouseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.newCageNo
     *
     * @return the value of rabbit_change_record.newCageNo
     *
     * @mbg.generated
     */
    public String getNewCageNo() {
        return newCageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.newCageNo
     *
     * @param newCageNo the value for rabbit_change_record.newCageNo
     *
     * @mbg.generated
     */
    public void setNewCageNo(String newCageNo) {
        this.newCageNo = newCageNo == null ? null : newCageNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.newRabbitHouseNo
     *
     * @return the value of rabbit_change_record.newRabbitHouseNo
     *
     * @mbg.generated
     */
    public String getNewRabbitHouseNo() {
        return newRabbitHouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.newRabbitHouseNo
     *
     * @param newRabbitHouseNo the value for rabbit_change_record.newRabbitHouseNo
     *
     * @mbg.generated
     */
    public void setNewRabbitHouseNo(String newRabbitHouseNo) {
        this.newRabbitHouseNo = newRabbitHouseNo == null ? null : newRabbitHouseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.actionUser
     *
     * @return the value of rabbit_change_record.actionUser
     *
     * @mbg.generated
     */
    public String getActionUser() {
        return actionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.actionUser
     *
     * @param actionUser the value for rabbit_change_record.actionUser
     *
     * @mbg.generated
     */
    public void setActionUser(String actionUser) {
        this.actionUser = actionUser == null ? null : actionUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_change_record.changeDate
     *
     * @return the value of rabbit_change_record.changeDate
     *
     * @mbg.generated
     */
    public Date getChangeDate() {
        return changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_change_record.changeDate
     *
     * @param changeDate the value for rabbit_change_record.changeDate
     *
     * @mbg.generated
     */
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_change_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recordId=").append(recordId);
        sb.append(", rabbitNo=").append(rabbitNo);
        sb.append(", sex=").append(sex);
        sb.append(", oldCageNo=").append(oldCageNo);
        sb.append(", oldRabbitHouseNo=").append(oldRabbitHouseNo);
        sb.append(", newCageNo=").append(newCageNo);
        sb.append(", newRabbitHouseNo=").append(newRabbitHouseNo);
        sb.append(", actionUser=").append(actionUser);
        sb.append(", changeDate=").append(changeDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}