package com.nwafu.databaseoprations.entity;

import java.io.Serializable;

public class RabbitHealth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.healRecordId
     *
     * @mbg.generated
     */
    private String healRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.farmUuid
     *
     * @mbg.generated
     */
    private String farmUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.rabbitHouseNo
     *
     * @mbg.generated
     */
    private Integer rabbitHouseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.rabbitNo
     *
     * @mbg.generated
     */
    private Integer rabbitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.bodyCondition
     *
     * @mbg.generated
     */
    private String bodyCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.mentalCondition
     *
     * @mbg.generated
     */
    private String mentalCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.feeding
     *
     * @mbg.generated
     */
    private String feeding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.drinking
     *
     * @mbg.generated
     */
    private String drinking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.eyelid
     *
     * @mbg.generated
     */
    private Integer eyelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.conjunctiva
     *
     * @mbg.generated
     */
    private String conjunctiva;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.secretion
     *
     * @mbg.generated
     */
    private String secretion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.externalEar
     *
     * @mbg.generated
     */
    private String externalEar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.innerEar
     *
     * @mbg.generated
     */
    private String innerEar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.nose
     *
     * @mbg.generated
     */
    private String nose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.nasalFluid
     *
     * @mbg.generated
     */
    private Integer nasalFluid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.nasalMucosa
     *
     * @mbg.generated
     */
    private String nasalMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.mouth
     *
     * @mbg.generated
     */
    private String mouth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.abdomen
     *
     * @mbg.generated
     */
    private String abdomen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.anus
     *
     * @mbg.generated
     */
    private String anus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.odor
     *
     * @mbg.generated
     */
    private String odor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.fecalMorphology
     *
     * @mbg.generated
     */
    private String fecalMorphology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.stoolColor
     *
     * @mbg.generated
     */
    private String stoolColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.urineColor
     *
     * @mbg.generated
     */
    private String urineColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.urineVolume
     *
     * @mbg.generated
     */
    private String urineVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.coat
     *
     * @mbg.generated
     */
    private String coat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.skin
     *
     * @mbg.generated
     */
    private String skin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.joint
     *
     * @mbg.generated
     */
    private String joint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.limbs
     *
     * @mbg.generated
     */
    private String limbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.suspectedDisease
     *
     * @mbg.generated
     */
    private String suspectedDisease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.medication
     *
     * @mbg.generated
     */
    private String medication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.initialTreatmentEffect
     *
     * @mbg.generated
     */
    private String initialTreatmentEffect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.muscle
     *
     * @mbg.generated
     */
    private String muscle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.brain
     *
     * @mbg.generated
     */
    private String brain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.cerebellum
     *
     * @mbg.generated
     */
    private String cerebellum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.throat
     *
     * @mbg.generated
     */
    private String throat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.organ
     *
     * @mbg.generated
     */
    private String organ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.abdominalCavity
     *
     * @mbg.generated
     */
    private String abdominalCavity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.thoracicCavity
     *
     * @mbg.generated
     */
    private String thoracicCavity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.lymphNode
     *
     * @mbg.generated
     */
    private String lymphNode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.heart
     *
     * @mbg.generated
     */
    private String heart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.lung
     *
     * @mbg.generated
     */
    private String lung;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.liver
     *
     * @mbg.generated
     */
    private String liver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.liverColor
     *
     * @mbg.generated
     */
    private String liverColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.gallbladder
     *
     * @mbg.generated
     */
    private String gallbladder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.bileDuct
     *
     * @mbg.generated
     */
    private String bileDuct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.kidneySurface
     *
     * @mbg.generated
     */
    private String kidneySurface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.renalParenchyma
     *
     * @mbg.generated
     */
    private String renalParenchyma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.spleen
     *
     * @mbg.generated
     */
    private String spleen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.gastricMucosa
     *
     * @mbg.generated
     */
    private String gastricMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.stomachContents
     *
     * @mbg.generated
     */
    private String stomachContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.duodenalMucosa
     *
     * @mbg.generated
     */
    private String duodenalMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.duodenalContents
     *
     * @mbg.generated
     */
    private String duodenalContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.jejunalMucosa
     *
     * @mbg.generated
     */
    private String jejunalMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.jejunalContents
     *
     * @mbg.generated
     */
    private String jejunalContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.ilealMucosa
     *
     * @mbg.generated
     */
    private String ilealMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.ilealContents
     *
     * @mbg.generated
     */
    private String ilealContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.cecumMucosa
     *
     * @mbg.generated
     */
    private String cecumMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.cecumContents
     *
     * @mbg.generated
     */
    private String cecumContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.appendix
     *
     * @mbg.generated
     */
    private String appendix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.colonicMucosa
     *
     * @mbg.generated
     */
    private String colonicMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.colonContents
     *
     * @mbg.generated
     */
    private String colonContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.rectalMucosa
     *
     * @mbg.generated
     */
    private String rectalMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.rectalContents
     *
     * @mbg.generated
     */
    private String rectalContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.vaginalMucosa
     *
     * @mbg.generated
     */
    private String vaginalMucosa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.vaginalDischarge
     *
     * @mbg.generated
     */
    private String vaginalDischarge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.uterus
     *
     * @mbg.generated
     */
    private String uterus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.ovaryAndFallopianTubes
     *
     * @mbg.generated
     */
    private String ovaryAndFallopianTubes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.breast
     *
     * @mbg.generated
     */
    private String breast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.penis
     *
     * @mbg.generated
     */
    private String penis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.testis
     *
     * @mbg.generated
     */
    private String testis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.scrotum
     *
     * @mbg.generated
     */
    private String scrotum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.anatomicalDiagnosis
     *
     * @mbg.generated
     */
    private String anatomicalDiagnosis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.microscopicExaminationResult
     *
     * @mbg.generated
     */
    private String microscopicExaminationResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.bacterialCultureConclusion
     *
     * @mbg.generated
     */
    private String bacterialCultureConclusion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_health.diagnosisConclusion
     *
     * @mbg.generated
     */
    private String diagnosisConclusion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rabbit_health
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.healRecordId
     *
     * @return the value of rabbit_health.healRecordId
     *
     * @mbg.generated
     */
    public String getHealRecordId() {
        return healRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.healRecordId
     *
     * @param healRecordId the value for rabbit_health.healRecordId
     *
     * @mbg.generated
     */
    public void setHealRecordId(String healRecordId) {
        this.healRecordId = healRecordId == null ? null : healRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.farmUuid
     *
     * @return the value of rabbit_health.farmUuid
     *
     * @mbg.generated
     */
    public String getFarmUuid() {
        return farmUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.farmUuid
     *
     * @param farmUuid the value for rabbit_health.farmUuid
     *
     * @mbg.generated
     */
    public void setFarmUuid(String farmUuid) {
        this.farmUuid = farmUuid == null ? null : farmUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.rabbitHouseNo
     *
     * @return the value of rabbit_health.rabbitHouseNo
     *
     * @mbg.generated
     */
    public Integer getRabbitHouseNo() {
        return rabbitHouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.rabbitHouseNo
     *
     * @param rabbitHouseNo the value for rabbit_health.rabbitHouseNo
     *
     * @mbg.generated
     */
    public void setRabbitHouseNo(Integer rabbitHouseNo) {
        this.rabbitHouseNo = rabbitHouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.rabbitNo
     *
     * @return the value of rabbit_health.rabbitNo
     *
     * @mbg.generated
     */
    public Integer getRabbitNo() {
        return rabbitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.rabbitNo
     *
     * @param rabbitNo the value for rabbit_health.rabbitNo
     *
     * @mbg.generated
     */
    public void setRabbitNo(Integer rabbitNo) {
        this.rabbitNo = rabbitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.bodyCondition
     *
     * @return the value of rabbit_health.bodyCondition
     *
     * @mbg.generated
     */
    public String getBodyCondition() {
        return bodyCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.bodyCondition
     *
     * @param bodyCondition the value for rabbit_health.bodyCondition
     *
     * @mbg.generated
     */
    public void setBodyCondition(String bodyCondition) {
        this.bodyCondition = bodyCondition == null ? null : bodyCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.mentalCondition
     *
     * @return the value of rabbit_health.mentalCondition
     *
     * @mbg.generated
     */
    public String getMentalCondition() {
        return mentalCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.mentalCondition
     *
     * @param mentalCondition the value for rabbit_health.mentalCondition
     *
     * @mbg.generated
     */
    public void setMentalCondition(String mentalCondition) {
        this.mentalCondition = mentalCondition == null ? null : mentalCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.feeding
     *
     * @return the value of rabbit_health.feeding
     *
     * @mbg.generated
     */
    public String getFeeding() {
        return feeding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.feeding
     *
     * @param feeding the value for rabbit_health.feeding
     *
     * @mbg.generated
     */
    public void setFeeding(String feeding) {
        this.feeding = feeding == null ? null : feeding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.drinking
     *
     * @return the value of rabbit_health.drinking
     *
     * @mbg.generated
     */
    public String getDrinking() {
        return drinking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.drinking
     *
     * @param drinking the value for rabbit_health.drinking
     *
     * @mbg.generated
     */
    public void setDrinking(String drinking) {
        this.drinking = drinking == null ? null : drinking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.eyelid
     *
     * @return the value of rabbit_health.eyelid
     *
     * @mbg.generated
     */
    public Integer getEyelid() {
        return eyelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.eyelid
     *
     * @param eyelid the value for rabbit_health.eyelid
     *
     * @mbg.generated
     */
    public void setEyelid(Integer eyelid) {
        this.eyelid = eyelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.conjunctiva
     *
     * @return the value of rabbit_health.conjunctiva
     *
     * @mbg.generated
     */
    public String getConjunctiva() {
        return conjunctiva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.conjunctiva
     *
     * @param conjunctiva the value for rabbit_health.conjunctiva
     *
     * @mbg.generated
     */
    public void setConjunctiva(String conjunctiva) {
        this.conjunctiva = conjunctiva == null ? null : conjunctiva.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.secretion
     *
     * @return the value of rabbit_health.secretion
     *
     * @mbg.generated
     */
    public String getSecretion() {
        return secretion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.secretion
     *
     * @param secretion the value for rabbit_health.secretion
     *
     * @mbg.generated
     */
    public void setSecretion(String secretion) {
        this.secretion = secretion == null ? null : secretion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.externalEar
     *
     * @return the value of rabbit_health.externalEar
     *
     * @mbg.generated
     */
    public String getExternalEar() {
        return externalEar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.externalEar
     *
     * @param externalEar the value for rabbit_health.externalEar
     *
     * @mbg.generated
     */
    public void setExternalEar(String externalEar) {
        this.externalEar = externalEar == null ? null : externalEar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.innerEar
     *
     * @return the value of rabbit_health.innerEar
     *
     * @mbg.generated
     */
    public String getInnerEar() {
        return innerEar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.innerEar
     *
     * @param innerEar the value for rabbit_health.innerEar
     *
     * @mbg.generated
     */
    public void setInnerEar(String innerEar) {
        this.innerEar = innerEar == null ? null : innerEar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.nose
     *
     * @return the value of rabbit_health.nose
     *
     * @mbg.generated
     */
    public String getNose() {
        return nose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.nose
     *
     * @param nose the value for rabbit_health.nose
     *
     * @mbg.generated
     */
    public void setNose(String nose) {
        this.nose = nose == null ? null : nose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.nasalFluid
     *
     * @return the value of rabbit_health.nasalFluid
     *
     * @mbg.generated
     */
    public Integer getNasalFluid() {
        return nasalFluid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.nasalFluid
     *
     * @param nasalFluid the value for rabbit_health.nasalFluid
     *
     * @mbg.generated
     */
    public void setNasalFluid(Integer nasalFluid) {
        this.nasalFluid = nasalFluid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.nasalMucosa
     *
     * @return the value of rabbit_health.nasalMucosa
     *
     * @mbg.generated
     */
    public String getNasalMucosa() {
        return nasalMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.nasalMucosa
     *
     * @param nasalMucosa the value for rabbit_health.nasalMucosa
     *
     * @mbg.generated
     */
    public void setNasalMucosa(String nasalMucosa) {
        this.nasalMucosa = nasalMucosa == null ? null : nasalMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.mouth
     *
     * @return the value of rabbit_health.mouth
     *
     * @mbg.generated
     */
    public String getMouth() {
        return mouth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.mouth
     *
     * @param mouth the value for rabbit_health.mouth
     *
     * @mbg.generated
     */
    public void setMouth(String mouth) {
        this.mouth = mouth == null ? null : mouth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.abdomen
     *
     * @return the value of rabbit_health.abdomen
     *
     * @mbg.generated
     */
    public String getAbdomen() {
        return abdomen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.abdomen
     *
     * @param abdomen the value for rabbit_health.abdomen
     *
     * @mbg.generated
     */
    public void setAbdomen(String abdomen) {
        this.abdomen = abdomen == null ? null : abdomen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.anus
     *
     * @return the value of rabbit_health.anus
     *
     * @mbg.generated
     */
    public String getAnus() {
        return anus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.anus
     *
     * @param anus the value for rabbit_health.anus
     *
     * @mbg.generated
     */
    public void setAnus(String anus) {
        this.anus = anus == null ? null : anus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.odor
     *
     * @return the value of rabbit_health.odor
     *
     * @mbg.generated
     */
    public String getOdor() {
        return odor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.odor
     *
     * @param odor the value for rabbit_health.odor
     *
     * @mbg.generated
     */
    public void setOdor(String odor) {
        this.odor = odor == null ? null : odor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.fecalMorphology
     *
     * @return the value of rabbit_health.fecalMorphology
     *
     * @mbg.generated
     */
    public String getFecalMorphology() {
        return fecalMorphology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.fecalMorphology
     *
     * @param fecalMorphology the value for rabbit_health.fecalMorphology
     *
     * @mbg.generated
     */
    public void setFecalMorphology(String fecalMorphology) {
        this.fecalMorphology = fecalMorphology == null ? null : fecalMorphology.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.stoolColor
     *
     * @return the value of rabbit_health.stoolColor
     *
     * @mbg.generated
     */
    public String getStoolColor() {
        return stoolColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.stoolColor
     *
     * @param stoolColor the value for rabbit_health.stoolColor
     *
     * @mbg.generated
     */
    public void setStoolColor(String stoolColor) {
        this.stoolColor = stoolColor == null ? null : stoolColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.urineColor
     *
     * @return the value of rabbit_health.urineColor
     *
     * @mbg.generated
     */
    public String getUrineColor() {
        return urineColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.urineColor
     *
     * @param urineColor the value for rabbit_health.urineColor
     *
     * @mbg.generated
     */
    public void setUrineColor(String urineColor) {
        this.urineColor = urineColor == null ? null : urineColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.urineVolume
     *
     * @return the value of rabbit_health.urineVolume
     *
     * @mbg.generated
     */
    public String getUrineVolume() {
        return urineVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.urineVolume
     *
     * @param urineVolume the value for rabbit_health.urineVolume
     *
     * @mbg.generated
     */
    public void setUrineVolume(String urineVolume) {
        this.urineVolume = urineVolume == null ? null : urineVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.coat
     *
     * @return the value of rabbit_health.coat
     *
     * @mbg.generated
     */
    public String getCoat() {
        return coat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.coat
     *
     * @param coat the value for rabbit_health.coat
     *
     * @mbg.generated
     */
    public void setCoat(String coat) {
        this.coat = coat == null ? null : coat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.skin
     *
     * @return the value of rabbit_health.skin
     *
     * @mbg.generated
     */
    public String getSkin() {
        return skin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.skin
     *
     * @param skin the value for rabbit_health.skin
     *
     * @mbg.generated
     */
    public void setSkin(String skin) {
        this.skin = skin == null ? null : skin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.joint
     *
     * @return the value of rabbit_health.joint
     *
     * @mbg.generated
     */
    public String getJoint() {
        return joint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.joint
     *
     * @param joint the value for rabbit_health.joint
     *
     * @mbg.generated
     */
    public void setJoint(String joint) {
        this.joint = joint == null ? null : joint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.limbs
     *
     * @return the value of rabbit_health.limbs
     *
     * @mbg.generated
     */
    public String getLimbs() {
        return limbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.limbs
     *
     * @param limbs the value for rabbit_health.limbs
     *
     * @mbg.generated
     */
    public void setLimbs(String limbs) {
        this.limbs = limbs == null ? null : limbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.suspectedDisease
     *
     * @return the value of rabbit_health.suspectedDisease
     *
     * @mbg.generated
     */
    public String getSuspectedDisease() {
        return suspectedDisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.suspectedDisease
     *
     * @param suspectedDisease the value for rabbit_health.suspectedDisease
     *
     * @mbg.generated
     */
    public void setSuspectedDisease(String suspectedDisease) {
        this.suspectedDisease = suspectedDisease == null ? null : suspectedDisease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.medication
     *
     * @return the value of rabbit_health.medication
     *
     * @mbg.generated
     */
    public String getMedication() {
        return medication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.medication
     *
     * @param medication the value for rabbit_health.medication
     *
     * @mbg.generated
     */
    public void setMedication(String medication) {
        this.medication = medication == null ? null : medication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.initialTreatmentEffect
     *
     * @return the value of rabbit_health.initialTreatmentEffect
     *
     * @mbg.generated
     */
    public String getInitialTreatmentEffect() {
        return initialTreatmentEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.initialTreatmentEffect
     *
     * @param initialTreatmentEffect the value for rabbit_health.initialTreatmentEffect
     *
     * @mbg.generated
     */
    public void setInitialTreatmentEffect(String initialTreatmentEffect) {
        this.initialTreatmentEffect = initialTreatmentEffect == null ? null : initialTreatmentEffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.muscle
     *
     * @return the value of rabbit_health.muscle
     *
     * @mbg.generated
     */
    public String getMuscle() {
        return muscle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.muscle
     *
     * @param muscle the value for rabbit_health.muscle
     *
     * @mbg.generated
     */
    public void setMuscle(String muscle) {
        this.muscle = muscle == null ? null : muscle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.brain
     *
     * @return the value of rabbit_health.brain
     *
     * @mbg.generated
     */
    public String getBrain() {
        return brain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.brain
     *
     * @param brain the value for rabbit_health.brain
     *
     * @mbg.generated
     */
    public void setBrain(String brain) {
        this.brain = brain == null ? null : brain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.cerebellum
     *
     * @return the value of rabbit_health.cerebellum
     *
     * @mbg.generated
     */
    public String getCerebellum() {
        return cerebellum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.cerebellum
     *
     * @param cerebellum the value for rabbit_health.cerebellum
     *
     * @mbg.generated
     */
    public void setCerebellum(String cerebellum) {
        this.cerebellum = cerebellum == null ? null : cerebellum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.throat
     *
     * @return the value of rabbit_health.throat
     *
     * @mbg.generated
     */
    public String getThroat() {
        return throat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.throat
     *
     * @param throat the value for rabbit_health.throat
     *
     * @mbg.generated
     */
    public void setThroat(String throat) {
        this.throat = throat == null ? null : throat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.organ
     *
     * @return the value of rabbit_health.organ
     *
     * @mbg.generated
     */
    public String getOrgan() {
        return organ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.organ
     *
     * @param organ the value for rabbit_health.organ
     *
     * @mbg.generated
     */
    public void setOrgan(String organ) {
        this.organ = organ == null ? null : organ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.abdominalCavity
     *
     * @return the value of rabbit_health.abdominalCavity
     *
     * @mbg.generated
     */
    public String getAbdominalCavity() {
        return abdominalCavity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.abdominalCavity
     *
     * @param abdominalCavity the value for rabbit_health.abdominalCavity
     *
     * @mbg.generated
     */
    public void setAbdominalCavity(String abdominalCavity) {
        this.abdominalCavity = abdominalCavity == null ? null : abdominalCavity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.thoracicCavity
     *
     * @return the value of rabbit_health.thoracicCavity
     *
     * @mbg.generated
     */
    public String getThoracicCavity() {
        return thoracicCavity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.thoracicCavity
     *
     * @param thoracicCavity the value for rabbit_health.thoracicCavity
     *
     * @mbg.generated
     */
    public void setThoracicCavity(String thoracicCavity) {
        this.thoracicCavity = thoracicCavity == null ? null : thoracicCavity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.lymphNode
     *
     * @return the value of rabbit_health.lymphNode
     *
     * @mbg.generated
     */
    public String getLymphNode() {
        return lymphNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.lymphNode
     *
     * @param lymphNode the value for rabbit_health.lymphNode
     *
     * @mbg.generated
     */
    public void setLymphNode(String lymphNode) {
        this.lymphNode = lymphNode == null ? null : lymphNode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.heart
     *
     * @return the value of rabbit_health.heart
     *
     * @mbg.generated
     */
    public String getHeart() {
        return heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.heart
     *
     * @param heart the value for rabbit_health.heart
     *
     * @mbg.generated
     */
    public void setHeart(String heart) {
        this.heart = heart == null ? null : heart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.lung
     *
     * @return the value of rabbit_health.lung
     *
     * @mbg.generated
     */
    public String getLung() {
        return lung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.lung
     *
     * @param lung the value for rabbit_health.lung
     *
     * @mbg.generated
     */
    public void setLung(String lung) {
        this.lung = lung == null ? null : lung.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.liver
     *
     * @return the value of rabbit_health.liver
     *
     * @mbg.generated
     */
    public String getLiver() {
        return liver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.liver
     *
     * @param liver the value for rabbit_health.liver
     *
     * @mbg.generated
     */
    public void setLiver(String liver) {
        this.liver = liver == null ? null : liver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.liverColor
     *
     * @return the value of rabbit_health.liverColor
     *
     * @mbg.generated
     */
    public String getLiverColor() {
        return liverColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.liverColor
     *
     * @param liverColor the value for rabbit_health.liverColor
     *
     * @mbg.generated
     */
    public void setLiverColor(String liverColor) {
        this.liverColor = liverColor == null ? null : liverColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.gallbladder
     *
     * @return the value of rabbit_health.gallbladder
     *
     * @mbg.generated
     */
    public String getGallbladder() {
        return gallbladder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.gallbladder
     *
     * @param gallbladder the value for rabbit_health.gallbladder
     *
     * @mbg.generated
     */
    public void setGallbladder(String gallbladder) {
        this.gallbladder = gallbladder == null ? null : gallbladder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.bileDuct
     *
     * @return the value of rabbit_health.bileDuct
     *
     * @mbg.generated
     */
    public String getBileDuct() {
        return bileDuct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.bileDuct
     *
     * @param bileDuct the value for rabbit_health.bileDuct
     *
     * @mbg.generated
     */
    public void setBileDuct(String bileDuct) {
        this.bileDuct = bileDuct == null ? null : bileDuct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.kidneySurface
     *
     * @return the value of rabbit_health.kidneySurface
     *
     * @mbg.generated
     */
    public String getKidneySurface() {
        return kidneySurface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.kidneySurface
     *
     * @param kidneySurface the value for rabbit_health.kidneySurface
     *
     * @mbg.generated
     */
    public void setKidneySurface(String kidneySurface) {
        this.kidneySurface = kidneySurface == null ? null : kidneySurface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.renalParenchyma
     *
     * @return the value of rabbit_health.renalParenchyma
     *
     * @mbg.generated
     */
    public String getRenalParenchyma() {
        return renalParenchyma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.renalParenchyma
     *
     * @param renalParenchyma the value for rabbit_health.renalParenchyma
     *
     * @mbg.generated
     */
    public void setRenalParenchyma(String renalParenchyma) {
        this.renalParenchyma = renalParenchyma == null ? null : renalParenchyma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.spleen
     *
     * @return the value of rabbit_health.spleen
     *
     * @mbg.generated
     */
    public String getSpleen() {
        return spleen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.spleen
     *
     * @param spleen the value for rabbit_health.spleen
     *
     * @mbg.generated
     */
    public void setSpleen(String spleen) {
        this.spleen = spleen == null ? null : spleen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.gastricMucosa
     *
     * @return the value of rabbit_health.gastricMucosa
     *
     * @mbg.generated
     */
    public String getGastricMucosa() {
        return gastricMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.gastricMucosa
     *
     * @param gastricMucosa the value for rabbit_health.gastricMucosa
     *
     * @mbg.generated
     */
    public void setGastricMucosa(String gastricMucosa) {
        this.gastricMucosa = gastricMucosa == null ? null : gastricMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.stomachContents
     *
     * @return the value of rabbit_health.stomachContents
     *
     * @mbg.generated
     */
    public String getStomachContents() {
        return stomachContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.stomachContents
     *
     * @param stomachContents the value for rabbit_health.stomachContents
     *
     * @mbg.generated
     */
    public void setStomachContents(String stomachContents) {
        this.stomachContents = stomachContents == null ? null : stomachContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.duodenalMucosa
     *
     * @return the value of rabbit_health.duodenalMucosa
     *
     * @mbg.generated
     */
    public String getDuodenalMucosa() {
        return duodenalMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.duodenalMucosa
     *
     * @param duodenalMucosa the value for rabbit_health.duodenalMucosa
     *
     * @mbg.generated
     */
    public void setDuodenalMucosa(String duodenalMucosa) {
        this.duodenalMucosa = duodenalMucosa == null ? null : duodenalMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.duodenalContents
     *
     * @return the value of rabbit_health.duodenalContents
     *
     * @mbg.generated
     */
    public String getDuodenalContents() {
        return duodenalContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.duodenalContents
     *
     * @param duodenalContents the value for rabbit_health.duodenalContents
     *
     * @mbg.generated
     */
    public void setDuodenalContents(String duodenalContents) {
        this.duodenalContents = duodenalContents == null ? null : duodenalContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.jejunalMucosa
     *
     * @return the value of rabbit_health.jejunalMucosa
     *
     * @mbg.generated
     */
    public String getJejunalMucosa() {
        return jejunalMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.jejunalMucosa
     *
     * @param jejunalMucosa the value for rabbit_health.jejunalMucosa
     *
     * @mbg.generated
     */
    public void setJejunalMucosa(String jejunalMucosa) {
        this.jejunalMucosa = jejunalMucosa == null ? null : jejunalMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.jejunalContents
     *
     * @return the value of rabbit_health.jejunalContents
     *
     * @mbg.generated
     */
    public String getJejunalContents() {
        return jejunalContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.jejunalContents
     *
     * @param jejunalContents the value for rabbit_health.jejunalContents
     *
     * @mbg.generated
     */
    public void setJejunalContents(String jejunalContents) {
        this.jejunalContents = jejunalContents == null ? null : jejunalContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.ilealMucosa
     *
     * @return the value of rabbit_health.ilealMucosa
     *
     * @mbg.generated
     */
    public String getIlealMucosa() {
        return ilealMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.ilealMucosa
     *
     * @param ilealMucosa the value for rabbit_health.ilealMucosa
     *
     * @mbg.generated
     */
    public void setIlealMucosa(String ilealMucosa) {
        this.ilealMucosa = ilealMucosa == null ? null : ilealMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.ilealContents
     *
     * @return the value of rabbit_health.ilealContents
     *
     * @mbg.generated
     */
    public String getIlealContents() {
        return ilealContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.ilealContents
     *
     * @param ilealContents the value for rabbit_health.ilealContents
     *
     * @mbg.generated
     */
    public void setIlealContents(String ilealContents) {
        this.ilealContents = ilealContents == null ? null : ilealContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.cecumMucosa
     *
     * @return the value of rabbit_health.cecumMucosa
     *
     * @mbg.generated
     */
    public String getCecumMucosa() {
        return cecumMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.cecumMucosa
     *
     * @param cecumMucosa the value for rabbit_health.cecumMucosa
     *
     * @mbg.generated
     */
    public void setCecumMucosa(String cecumMucosa) {
        this.cecumMucosa = cecumMucosa == null ? null : cecumMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.cecumContents
     *
     * @return the value of rabbit_health.cecumContents
     *
     * @mbg.generated
     */
    public String getCecumContents() {
        return cecumContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.cecumContents
     *
     * @param cecumContents the value for rabbit_health.cecumContents
     *
     * @mbg.generated
     */
    public void setCecumContents(String cecumContents) {
        this.cecumContents = cecumContents == null ? null : cecumContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.appendix
     *
     * @return the value of rabbit_health.appendix
     *
     * @mbg.generated
     */
    public String getAppendix() {
        return appendix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.appendix
     *
     * @param appendix the value for rabbit_health.appendix
     *
     * @mbg.generated
     */
    public void setAppendix(String appendix) {
        this.appendix = appendix == null ? null : appendix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.colonicMucosa
     *
     * @return the value of rabbit_health.colonicMucosa
     *
     * @mbg.generated
     */
    public String getColonicMucosa() {
        return colonicMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.colonicMucosa
     *
     * @param colonicMucosa the value for rabbit_health.colonicMucosa
     *
     * @mbg.generated
     */
    public void setColonicMucosa(String colonicMucosa) {
        this.colonicMucosa = colonicMucosa == null ? null : colonicMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.colonContents
     *
     * @return the value of rabbit_health.colonContents
     *
     * @mbg.generated
     */
    public String getColonContents() {
        return colonContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.colonContents
     *
     * @param colonContents the value for rabbit_health.colonContents
     *
     * @mbg.generated
     */
    public void setColonContents(String colonContents) {
        this.colonContents = colonContents == null ? null : colonContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.rectalMucosa
     *
     * @return the value of rabbit_health.rectalMucosa
     *
     * @mbg.generated
     */
    public String getRectalMucosa() {
        return rectalMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.rectalMucosa
     *
     * @param rectalMucosa the value for rabbit_health.rectalMucosa
     *
     * @mbg.generated
     */
    public void setRectalMucosa(String rectalMucosa) {
        this.rectalMucosa = rectalMucosa == null ? null : rectalMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.rectalContents
     *
     * @return the value of rabbit_health.rectalContents
     *
     * @mbg.generated
     */
    public String getRectalContents() {
        return rectalContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.rectalContents
     *
     * @param rectalContents the value for rabbit_health.rectalContents
     *
     * @mbg.generated
     */
    public void setRectalContents(String rectalContents) {
        this.rectalContents = rectalContents == null ? null : rectalContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.vaginalMucosa
     *
     * @return the value of rabbit_health.vaginalMucosa
     *
     * @mbg.generated
     */
    public String getVaginalMucosa() {
        return vaginalMucosa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.vaginalMucosa
     *
     * @param vaginalMucosa the value for rabbit_health.vaginalMucosa
     *
     * @mbg.generated
     */
    public void setVaginalMucosa(String vaginalMucosa) {
        this.vaginalMucosa = vaginalMucosa == null ? null : vaginalMucosa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.vaginalDischarge
     *
     * @return the value of rabbit_health.vaginalDischarge
     *
     * @mbg.generated
     */
    public String getVaginalDischarge() {
        return vaginalDischarge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.vaginalDischarge
     *
     * @param vaginalDischarge the value for rabbit_health.vaginalDischarge
     *
     * @mbg.generated
     */
    public void setVaginalDischarge(String vaginalDischarge) {
        this.vaginalDischarge = vaginalDischarge == null ? null : vaginalDischarge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.uterus
     *
     * @return the value of rabbit_health.uterus
     *
     * @mbg.generated
     */
    public String getUterus() {
        return uterus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.uterus
     *
     * @param uterus the value for rabbit_health.uterus
     *
     * @mbg.generated
     */
    public void setUterus(String uterus) {
        this.uterus = uterus == null ? null : uterus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.ovaryAndFallopianTubes
     *
     * @return the value of rabbit_health.ovaryAndFallopianTubes
     *
     * @mbg.generated
     */
    public String getOvaryAndFallopianTubes() {
        return ovaryAndFallopianTubes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.ovaryAndFallopianTubes
     *
     * @param ovaryAndFallopianTubes the value for rabbit_health.ovaryAndFallopianTubes
     *
     * @mbg.generated
     */
    public void setOvaryAndFallopianTubes(String ovaryAndFallopianTubes) {
        this.ovaryAndFallopianTubes = ovaryAndFallopianTubes == null ? null : ovaryAndFallopianTubes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.breast
     *
     * @return the value of rabbit_health.breast
     *
     * @mbg.generated
     */
    public String getBreast() {
        return breast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.breast
     *
     * @param breast the value for rabbit_health.breast
     *
     * @mbg.generated
     */
    public void setBreast(String breast) {
        this.breast = breast == null ? null : breast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.penis
     *
     * @return the value of rabbit_health.penis
     *
     * @mbg.generated
     */
    public String getPenis() {
        return penis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.penis
     *
     * @param penis the value for rabbit_health.penis
     *
     * @mbg.generated
     */
    public void setPenis(String penis) {
        this.penis = penis == null ? null : penis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.testis
     *
     * @return the value of rabbit_health.testis
     *
     * @mbg.generated
     */
    public String getTestis() {
        return testis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.testis
     *
     * @param testis the value for rabbit_health.testis
     *
     * @mbg.generated
     */
    public void setTestis(String testis) {
        this.testis = testis == null ? null : testis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.scrotum
     *
     * @return the value of rabbit_health.scrotum
     *
     * @mbg.generated
     */
    public String getScrotum() {
        return scrotum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.scrotum
     *
     * @param scrotum the value for rabbit_health.scrotum
     *
     * @mbg.generated
     */
    public void setScrotum(String scrotum) {
        this.scrotum = scrotum == null ? null : scrotum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.anatomicalDiagnosis
     *
     * @return the value of rabbit_health.anatomicalDiagnosis
     *
     * @mbg.generated
     */
    public String getAnatomicalDiagnosis() {
        return anatomicalDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.anatomicalDiagnosis
     *
     * @param anatomicalDiagnosis the value for rabbit_health.anatomicalDiagnosis
     *
     * @mbg.generated
     */
    public void setAnatomicalDiagnosis(String anatomicalDiagnosis) {
        this.anatomicalDiagnosis = anatomicalDiagnosis == null ? null : anatomicalDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.microscopicExaminationResult
     *
     * @return the value of rabbit_health.microscopicExaminationResult
     *
     * @mbg.generated
     */
    public String getMicroscopicExaminationResult() {
        return microscopicExaminationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.microscopicExaminationResult
     *
     * @param microscopicExaminationResult the value for rabbit_health.microscopicExaminationResult
     *
     * @mbg.generated
     */
    public void setMicroscopicExaminationResult(String microscopicExaminationResult) {
        this.microscopicExaminationResult = microscopicExaminationResult == null ? null : microscopicExaminationResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.bacterialCultureConclusion
     *
     * @return the value of rabbit_health.bacterialCultureConclusion
     *
     * @mbg.generated
     */
    public String getBacterialCultureConclusion() {
        return bacterialCultureConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.bacterialCultureConclusion
     *
     * @param bacterialCultureConclusion the value for rabbit_health.bacterialCultureConclusion
     *
     * @mbg.generated
     */
    public void setBacterialCultureConclusion(String bacterialCultureConclusion) {
        this.bacterialCultureConclusion = bacterialCultureConclusion == null ? null : bacterialCultureConclusion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_health.diagnosisConclusion
     *
     * @return the value of rabbit_health.diagnosisConclusion
     *
     * @mbg.generated
     */
    public String getDiagnosisConclusion() {
        return diagnosisConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_health.diagnosisConclusion
     *
     * @param diagnosisConclusion the value for rabbit_health.diagnosisConclusion
     *
     * @mbg.generated
     */
    public void setDiagnosisConclusion(String diagnosisConclusion) {
        this.diagnosisConclusion = diagnosisConclusion == null ? null : diagnosisConclusion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_health
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", healRecordId=").append(healRecordId);
        sb.append(", farmUuid=").append(farmUuid);
        sb.append(", rabbitHouseNo=").append(rabbitHouseNo);
        sb.append(", rabbitNo=").append(rabbitNo);
        sb.append(", bodyCondition=").append(bodyCondition);
        sb.append(", mentalCondition=").append(mentalCondition);
        sb.append(", feeding=").append(feeding);
        sb.append(", drinking=").append(drinking);
        sb.append(", eyelid=").append(eyelid);
        sb.append(", conjunctiva=").append(conjunctiva);
        sb.append(", secretion=").append(secretion);
        sb.append(", externalEar=").append(externalEar);
        sb.append(", innerEar=").append(innerEar);
        sb.append(", nose=").append(nose);
        sb.append(", nasalFluid=").append(nasalFluid);
        sb.append(", nasalMucosa=").append(nasalMucosa);
        sb.append(", mouth=").append(mouth);
        sb.append(", abdomen=").append(abdomen);
        sb.append(", anus=").append(anus);
        sb.append(", odor=").append(odor);
        sb.append(", fecalMorphology=").append(fecalMorphology);
        sb.append(", stoolColor=").append(stoolColor);
        sb.append(", urineColor=").append(urineColor);
        sb.append(", urineVolume=").append(urineVolume);
        sb.append(", coat=").append(coat);
        sb.append(", skin=").append(skin);
        sb.append(", joint=").append(joint);
        sb.append(", limbs=").append(limbs);
        sb.append(", suspectedDisease=").append(suspectedDisease);
        sb.append(", medication=").append(medication);
        sb.append(", initialTreatmentEffect=").append(initialTreatmentEffect);
        sb.append(", muscle=").append(muscle);
        sb.append(", brain=").append(brain);
        sb.append(", cerebellum=").append(cerebellum);
        sb.append(", throat=").append(throat);
        sb.append(", organ=").append(organ);
        sb.append(", abdominalCavity=").append(abdominalCavity);
        sb.append(", thoracicCavity=").append(thoracicCavity);
        sb.append(", lymphNode=").append(lymphNode);
        sb.append(", heart=").append(heart);
        sb.append(", lung=").append(lung);
        sb.append(", liver=").append(liver);
        sb.append(", liverColor=").append(liverColor);
        sb.append(", gallbladder=").append(gallbladder);
        sb.append(", bileDuct=").append(bileDuct);
        sb.append(", kidneySurface=").append(kidneySurface);
        sb.append(", renalParenchyma=").append(renalParenchyma);
        sb.append(", spleen=").append(spleen);
        sb.append(", gastricMucosa=").append(gastricMucosa);
        sb.append(", stomachContents=").append(stomachContents);
        sb.append(", duodenalMucosa=").append(duodenalMucosa);
        sb.append(", duodenalContents=").append(duodenalContents);
        sb.append(", jejunalMucosa=").append(jejunalMucosa);
        sb.append(", jejunalContents=").append(jejunalContents);
        sb.append(", ilealMucosa=").append(ilealMucosa);
        sb.append(", ilealContents=").append(ilealContents);
        sb.append(", cecumMucosa=").append(cecumMucosa);
        sb.append(", cecumContents=").append(cecumContents);
        sb.append(", appendix=").append(appendix);
        sb.append(", colonicMucosa=").append(colonicMucosa);
        sb.append(", colonContents=").append(colonContents);
        sb.append(", rectalMucosa=").append(rectalMucosa);
        sb.append(", rectalContents=").append(rectalContents);
        sb.append(", vaginalMucosa=").append(vaginalMucosa);
        sb.append(", vaginalDischarge=").append(vaginalDischarge);
        sb.append(", uterus=").append(uterus);
        sb.append(", ovaryAndFallopianTubes=").append(ovaryAndFallopianTubes);
        sb.append(", breast=").append(breast);
        sb.append(", penis=").append(penis);
        sb.append(", testis=").append(testis);
        sb.append(", scrotum=").append(scrotum);
        sb.append(", anatomicalDiagnosis=").append(anatomicalDiagnosis);
        sb.append(", microscopicExaminationResult=").append(microscopicExaminationResult);
        sb.append(", bacterialCultureConclusion=").append(bacterialCultureConclusion);
        sb.append(", diagnosisConclusion=").append(diagnosisConclusion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}