package com.nwafu.databaseoprations.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nwafu.databaseoprations.config.DateJsonDeserializer;

import java.io.Serializable;
import java.util.Date;

public class RabbitBreeding implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.breedingInformationId
     *
     * @mbg.generated
     */
    private Integer breedingInformationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.femaleRabbitNo
     *
     * @mbg.generated
     */
    private String femaleRabbitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.maleRabbitNo
     *
     * @mbg.generated
     */
    private String maleRabbitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.breedingTime
     *
     * @mbg.generated
     */
    @JsonDeserialize(using = DateJsonDeserializer.class)
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date breedingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.twelveDayMoldTire
     *
     * @mbg.generated
     */
    private String twelveDayMoldTire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.birthTime
     *
     * @mbg.generated
     */
    @JsonDeserialize(using = DateJsonDeserializer.class)
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date birthTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.nestLittersNumber
     *
     * @mbg.generated
     */
    private Integer nestLittersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.nestLiveRabbitsNumber
     *
     * @mbg.generated
     */
    private Integer nestLiveRabbitsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.nestLiveRabbitsRate
     *
     * @mbg.generated
     */
    private Double nestLiveRabbitsRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.nestWeakDeadRabbitsNumber
     *
     * @mbg.generated
     */
    private Integer nestWeakDeadRabbitsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.nestWeakDeadRabbitsRate
     *
     * @mbg.generated
     */
    private Double nestWeakDeadRabbitsRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.nestWeakRabbitsNumber
     *
     * @mbg.generated
     */
    private Integer nestWeakRabbitsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.nestWeakRabbitsRate
     *
     * @mbg.generated
     */
    private Double nestWeakRabbitsRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.nestDeathRabbitRate
     *
     * @mbg.generated
     */
    private Double nestDeathRabbitRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.deathRabbitRate
     *
     * @mbg.generated
     */
    private Double deathRabbitRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.newbornNestWeight
     *
     * @mbg.generated
     */
    private Double newbornNestWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.newbornAverageWeight
     *
     * @mbg.generated
     */
    private Double newbornAverageWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.sucklingRabbitsNumber
     *
     * @mbg.generated
     */
    private Integer sucklingRabbitsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.twentyOneDaysOldNestWeight
     *
     * @mbg.generated
     */
    private Double twentyOneDaysOldNestWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.weaningNestWeight
     *
     * @mbg.generated
     */
    private Double weaningNestWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.lactationAverageDailyGain
     *
     * @mbg.generated
     */
    private Double lactationAverageDailyGain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.lactationConsumption
     *
     * @mbg.generated
     */
    private Double lactationConsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.lactationAverageMaterialWeightRatio
     *
     * @mbg.generated
     */
    private Double lactationAverageMaterialWeightRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_breeding.tiresNumber
     *
     * @mbg.generated
     */
    private String tiresNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rabbit_breeding
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.breedingInformationId
     *
     * @return the value of rabbit_breeding.breedingInformationId
     *
     * @mbg.generated
     */
    public Integer getBreedingInformationId() {
        return breedingInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.breedingInformationId
     *
     * @param breedingInformationId the value for rabbit_breeding.breedingInformationId
     *
     * @mbg.generated
     */
    public void setBreedingInformationId(Integer breedingInformationId) {
        this.breedingInformationId = breedingInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.femaleRabbitNo
     *
     * @return the value of rabbit_breeding.femaleRabbitNo
     *
     * @mbg.generated
     */
    public String getFemaleRabbitNo() {
        return femaleRabbitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.femaleRabbitNo
     *
     * @param femaleRabbitNo the value for rabbit_breeding.femaleRabbitNo
     *
     * @mbg.generated
     */
    public void setFemaleRabbitNo(String femaleRabbitNo) {
        this.femaleRabbitNo = femaleRabbitNo == null ? null : femaleRabbitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.maleRabbitNo
     *
     * @return the value of rabbit_breeding.maleRabbitNo
     *
     * @mbg.generated
     */
    public String getMaleRabbitNo() {
        return maleRabbitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.maleRabbitNo
     *
     * @param maleRabbitNo the value for rabbit_breeding.maleRabbitNo
     *
     * @mbg.generated
     */
    public void setMaleRabbitNo(String maleRabbitNo) {
        this.maleRabbitNo = maleRabbitNo == null ? null : maleRabbitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.breedingTime
     *
     * @return the value of rabbit_breeding.breedingTime
     *
     * @mbg.generated
     */
    public Date getBreedingTime() {
        return breedingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.breedingTime
     *
     * @param breedingTime the value for rabbit_breeding.breedingTime
     *
     * @mbg.generated
     */
    public void setBreedingTime(Date breedingTime) {
        this.breedingTime = breedingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.twelveDayMoldTire
     *
     * @return the value of rabbit_breeding.twelveDayMoldTire
     *
     * @mbg.generated
     */
    public String getTwelveDayMoldTire() {
        return twelveDayMoldTire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.twelveDayMoldTire
     *
     * @param twelveDayMoldTire the value for rabbit_breeding.twelveDayMoldTire
     *
     * @mbg.generated
     */
    public void setTwelveDayMoldTire(String twelveDayMoldTire) {
        this.twelveDayMoldTire = twelveDayMoldTire == null ? null : twelveDayMoldTire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.birthTime
     *
     * @return the value of rabbit_breeding.birthTime
     *
     * @mbg.generated
     */
    public Date getBirthTime() {
        return birthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.birthTime
     *
     * @param birthTime the value for rabbit_breeding.birthTime
     *
     * @mbg.generated
     */
    public void setBirthTime(Date birthTime) {
        this.birthTime = birthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.nestLittersNumber
     *
     * @return the value of rabbit_breeding.nestLittersNumber
     *
     * @mbg.generated
     */
    public Integer getNestLittersNumber() {
        return nestLittersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.nestLittersNumber
     *
     * @param nestLittersNumber the value for rabbit_breeding.nestLittersNumber
     *
     * @mbg.generated
     */
    public void setNestLittersNumber(Integer nestLittersNumber) {
        this.nestLittersNumber = nestLittersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.nestLiveRabbitsNumber
     *
     * @return the value of rabbit_breeding.nestLiveRabbitsNumber
     *
     * @mbg.generated
     */
    public Integer getNestLiveRabbitsNumber() {
        return nestLiveRabbitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.nestLiveRabbitsNumber
     *
     * @param nestLiveRabbitsNumber the value for rabbit_breeding.nestLiveRabbitsNumber
     *
     * @mbg.generated
     */
    public void setNestLiveRabbitsNumber(Integer nestLiveRabbitsNumber) {
        this.nestLiveRabbitsNumber = nestLiveRabbitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.nestLiveRabbitsRate
     *
     * @return the value of rabbit_breeding.nestLiveRabbitsRate
     *
     * @mbg.generated
     */
    public Double getNestLiveRabbitsRate() {
        return nestLiveRabbitsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.nestLiveRabbitsRate
     *
     * @param nestLiveRabbitsRate the value for rabbit_breeding.nestLiveRabbitsRate
     *
     * @mbg.generated
     */
    public void setNestLiveRabbitsRate(Double nestLiveRabbitsRate) {
        this.nestLiveRabbitsRate = nestLiveRabbitsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.nestWeakDeadRabbitsNumber
     *
     * @return the value of rabbit_breeding.nestWeakDeadRabbitsNumber
     *
     * @mbg.generated
     */
    public Integer getNestWeakDeadRabbitsNumber() {
        return nestWeakDeadRabbitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.nestWeakDeadRabbitsNumber
     *
     * @param nestWeakDeadRabbitsNumber the value for rabbit_breeding.nestWeakDeadRabbitsNumber
     *
     * @mbg.generated
     */
    public void setNestWeakDeadRabbitsNumber(Integer nestWeakDeadRabbitsNumber) {
        this.nestWeakDeadRabbitsNumber = nestWeakDeadRabbitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.nestWeakDeadRabbitsRate
     *
     * @return the value of rabbit_breeding.nestWeakDeadRabbitsRate
     *
     * @mbg.generated
     */
    public Double getNestWeakDeadRabbitsRate() {
        return nestWeakDeadRabbitsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.nestWeakDeadRabbitsRate
     *
     * @param nestWeakDeadRabbitsRate the value for rabbit_breeding.nestWeakDeadRabbitsRate
     *
     * @mbg.generated
     */
    public void setNestWeakDeadRabbitsRate(Double nestWeakDeadRabbitsRate) {
        this.nestWeakDeadRabbitsRate = nestWeakDeadRabbitsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.nestWeakRabbitsNumber
     *
     * @return the value of rabbit_breeding.nestWeakRabbitsNumber
     *
     * @mbg.generated
     */
    public Integer getNestWeakRabbitsNumber() {
        return nestWeakRabbitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.nestWeakRabbitsNumber
     *
     * @param nestWeakRabbitsNumber the value for rabbit_breeding.nestWeakRabbitsNumber
     *
     * @mbg.generated
     */
    public void setNestWeakRabbitsNumber(Integer nestWeakRabbitsNumber) {
        this.nestWeakRabbitsNumber = nestWeakRabbitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.nestWeakRabbitsRate
     *
     * @return the value of rabbit_breeding.nestWeakRabbitsRate
     *
     * @mbg.generated
     */
    public Double getNestWeakRabbitsRate() {
        return nestWeakRabbitsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.nestWeakRabbitsRate
     *
     * @param nestWeakRabbitsRate the value for rabbit_breeding.nestWeakRabbitsRate
     *
     * @mbg.generated
     */
    public void setNestWeakRabbitsRate(Double nestWeakRabbitsRate) {
        this.nestWeakRabbitsRate = nestWeakRabbitsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.nestDeathRabbitRate
     *
     * @return the value of rabbit_breeding.nestDeathRabbitRate
     *
     * @mbg.generated
     */
    public Double getNestDeathRabbitRate() {
        return nestDeathRabbitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.nestDeathRabbitRate
     *
     * @param nestDeathRabbitRate the value for rabbit_breeding.nestDeathRabbitRate
     *
     * @mbg.generated
     */
    public void setNestDeathRabbitRate(Double nestDeathRabbitRate) {
        this.nestDeathRabbitRate = nestDeathRabbitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.deathRabbitRate
     *
     * @return the value of rabbit_breeding.deathRabbitRate
     *
     * @mbg.generated
     */
    public Double getDeathRabbitRate() {
        return deathRabbitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.deathRabbitRate
     *
     * @param deathRabbitRate the value for rabbit_breeding.deathRabbitRate
     *
     * @mbg.generated
     */
    public void setDeathRabbitRate(Double deathRabbitRate) {
        this.deathRabbitRate = deathRabbitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.newbornNestWeight
     *
     * @return the value of rabbit_breeding.newbornNestWeight
     *
     * @mbg.generated
     */
    public Double getNewbornNestWeight() {
        return newbornNestWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.newbornNestWeight
     *
     * @param newbornNestWeight the value for rabbit_breeding.newbornNestWeight
     *
     * @mbg.generated
     */
    public void setNewbornNestWeight(Double newbornNestWeight) {
        this.newbornNestWeight = newbornNestWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.newbornAverageWeight
     *
     * @return the value of rabbit_breeding.newbornAverageWeight
     *
     * @mbg.generated
     */
    public Double getNewbornAverageWeight() {
        return newbornAverageWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.newbornAverageWeight
     *
     * @param newbornAverageWeight the value for rabbit_breeding.newbornAverageWeight
     *
     * @mbg.generated
     */
    public void setNewbornAverageWeight(Double newbornAverageWeight) {
        this.newbornAverageWeight = newbornAverageWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.sucklingRabbitsNumber
     *
     * @return the value of rabbit_breeding.sucklingRabbitsNumber
     *
     * @mbg.generated
     */
    public Integer getSucklingRabbitsNumber() {
        return sucklingRabbitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.sucklingRabbitsNumber
     *
     * @param sucklingRabbitsNumber the value for rabbit_breeding.sucklingRabbitsNumber
     *
     * @mbg.generated
     */
    public void setSucklingRabbitsNumber(Integer sucklingRabbitsNumber) {
        this.sucklingRabbitsNumber = sucklingRabbitsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.twentyOneDaysOldNestWeight
     *
     * @return the value of rabbit_breeding.twentyOneDaysOldNestWeight
     *
     * @mbg.generated
     */
    public Double getTwentyOneDaysOldNestWeight() {
        return twentyOneDaysOldNestWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.twentyOneDaysOldNestWeight
     *
     * @param twentyOneDaysOldNestWeight the value for rabbit_breeding.twentyOneDaysOldNestWeight
     *
     * @mbg.generated
     */
    public void setTwentyOneDaysOldNestWeight(Double twentyOneDaysOldNestWeight) {
        this.twentyOneDaysOldNestWeight = twentyOneDaysOldNestWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.weaningNestWeight
     *
     * @return the value of rabbit_breeding.weaningNestWeight
     *
     * @mbg.generated
     */
    public Double getWeaningNestWeight() {
        return weaningNestWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.weaningNestWeight
     *
     * @param weaningNestWeight the value for rabbit_breeding.weaningNestWeight
     *
     * @mbg.generated
     */
    public void setWeaningNestWeight(Double weaningNestWeight) {
        this.weaningNestWeight = weaningNestWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.lactationAverageDailyGain
     *
     * @return the value of rabbit_breeding.lactationAverageDailyGain
     *
     * @mbg.generated
     */
    public Double getLactationAverageDailyGain() {
        return lactationAverageDailyGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.lactationAverageDailyGain
     *
     * @param lactationAverageDailyGain the value for rabbit_breeding.lactationAverageDailyGain
     *
     * @mbg.generated
     */
    public void setLactationAverageDailyGain(Double lactationAverageDailyGain) {
        this.lactationAverageDailyGain = lactationAverageDailyGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.lactationConsumption
     *
     * @return the value of rabbit_breeding.lactationConsumption
     *
     * @mbg.generated
     */
    public Double getLactationConsumption() {
        return lactationConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.lactationConsumption
     *
     * @param lactationConsumption the value for rabbit_breeding.lactationConsumption
     *
     * @mbg.generated
     */
    public void setLactationConsumption(Double lactationConsumption) {
        this.lactationConsumption = lactationConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.lactationAverageMaterialWeightRatio
     *
     * @return the value of rabbit_breeding.lactationAverageMaterialWeightRatio
     *
     * @mbg.generated
     */
    public Double getLactationAverageMaterialWeightRatio() {
        return lactationAverageMaterialWeightRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.lactationAverageMaterialWeightRatio
     *
     * @param lactationAverageMaterialWeightRatio the value for rabbit_breeding.lactationAverageMaterialWeightRatio
     *
     * @mbg.generated
     */
    public void setLactationAverageMaterialWeightRatio(Double lactationAverageMaterialWeightRatio) {
        this.lactationAverageMaterialWeightRatio = lactationAverageMaterialWeightRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_breeding.tiresNumber
     *
     * @return the value of rabbit_breeding.tiresNumber
     *
     * @mbg.generated
     */
    public String getTiresNumber() {
        return tiresNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_breeding.tiresNumber
     *
     * @param tiresNumber the value for rabbit_breeding.tiresNumber
     *
     * @mbg.generated
     */
    public void setTiresNumber(String tiresNumber) {
        this.tiresNumber = tiresNumber == null ? null : tiresNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_breeding
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", breedingInformationId=").append(breedingInformationId);
        sb.append(", femaleRabbitNo=").append(femaleRabbitNo);
        sb.append(", maleRabbitNo=").append(maleRabbitNo);
        sb.append(", breedingTime=").append(breedingTime);
        sb.append(", twelveDayMoldTire=").append(twelveDayMoldTire);
        sb.append(", birthTime=").append(birthTime);
        sb.append(", nestLittersNumber=").append(nestLittersNumber);
        sb.append(", nestLiveRabbitsNumber=").append(nestLiveRabbitsNumber);
        sb.append(", nestLiveRabbitsRate=").append(nestLiveRabbitsRate);
        sb.append(", nestWeakDeadRabbitsNumber=").append(nestWeakDeadRabbitsNumber);
        sb.append(", nestWeakDeadRabbitsRate=").append(nestWeakDeadRabbitsRate);
        sb.append(", nestWeakRabbitsNumber=").append(nestWeakRabbitsNumber);
        sb.append(", nestWeakRabbitsRate=").append(nestWeakRabbitsRate);
        sb.append(", nestDeathRabbitRate=").append(nestDeathRabbitRate);
        sb.append(", deathRabbitRate=").append(deathRabbitRate);
        sb.append(", newbornNestWeight=").append(newbornNestWeight);
        sb.append(", newbornAverageWeight=").append(newbornAverageWeight);
        sb.append(", sucklingRabbitsNumber=").append(sucklingRabbitsNumber);
        sb.append(", twentyOneDaysOldNestWeight=").append(twentyOneDaysOldNestWeight);
        sb.append(", weaningNestWeight=").append(weaningNestWeight);
        sb.append(", lactationAverageDailyGain=").append(lactationAverageDailyGain);
        sb.append(", lactationConsumption=").append(lactationConsumption);
        sb.append(", lactationAverageMaterialWeightRatio=").append(lactationAverageMaterialWeightRatio);
        sb.append(", tiresNumber=").append(tiresNumber);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}