package com.nwafu.databaseoprations.entity;

import java.io.Serializable;
import java.util.Date;

public class RabbitInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.rabbitNo
     *
     * @mbg.generated
     */
    private String rabbitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.cageNo
     *
     * @mbg.generated
     */
    private String cageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.birthParity
     *
     * @mbg.generated
     */
    private Integer birthParity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.initialWeight
     *
     * @mbg.generated
     */
    private Double initialWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.coatGloss
     *
     * @mbg.generated
     */
    private String coatGloss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.rabbitHouseNo
     *
     * @mbg.generated
     */
    private String rabbitHouseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.identicalRabbits
     *
     * @mbg.generated
     */
    private Integer identicalRabbits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.economiType
     *
     * @mbg.generated
     */
    private String economiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.initialAge
     *
     * @mbg.generated
     */
    private String initialAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.fineHairType
     *
     * @mbg.generated
     */
    private String fineHairType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.origin
     *
     * @mbg.generated
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.mainCoatColor
     *
     * @mbg.generated
     */
    private String mainCoatColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.paternalNo
     *
     * @mbg.generated
     */
    private String paternalNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.coatFeature
     *
     * @mbg.generated
     */
    private String coatFeature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.maternalNo
     *
     * @mbg.generated
     */
    private String maternalNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.roughType
     *
     * @mbg.generated
     */
    private String roughType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.coatColor
     *
     * @mbg.generated
     */
    private String coatColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.bornDate
     *
     * @mbg.generated
     */
    private Date bornDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.nipplesNumber
     *
     * @mbg.generated
     */
    private Integer nipplesNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rabbit_info.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rabbit_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.rabbitNo
     *
     * @return the value of rabbit_info.rabbitNo
     *
     * @mbg.generated
     */
    public String getRabbitNo() {
        return rabbitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.rabbitNo
     *
     * @param rabbitNo the value for rabbit_info.rabbitNo
     *
     * @mbg.generated
     */
    public void setRabbitNo(String rabbitNo) {
        this.rabbitNo = rabbitNo == null ? null : rabbitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.cageNo
     *
     * @return the value of rabbit_info.cageNo
     *
     * @mbg.generated
     */
    public String getCageNo() {
        return cageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.cageNo
     *
     * @param cageNo the value for rabbit_info.cageNo
     *
     * @mbg.generated
     */
    public void setCageNo(String cageNo) {
        this.cageNo = cageNo == null ? null : cageNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.birthParity
     *
     * @return the value of rabbit_info.birthParity
     *
     * @mbg.generated
     */
    public Integer getBirthParity() {
        return birthParity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.birthParity
     *
     * @param birthParity the value for rabbit_info.birthParity
     *
     * @mbg.generated
     */
    public void setBirthParity(Integer birthParity) {
        this.birthParity = birthParity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.initialWeight
     *
     * @return the value of rabbit_info.initialWeight
     *
     * @mbg.generated
     */
    public Double getInitialWeight() {
        return initialWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.initialWeight
     *
     * @param initialWeight the value for rabbit_info.initialWeight
     *
     * @mbg.generated
     */
    public void setInitialWeight(Double initialWeight) {
        this.initialWeight = initialWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.coatGloss
     *
     * @return the value of rabbit_info.coatGloss
     *
     * @mbg.generated
     */
    public String getCoatGloss() {
        return coatGloss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.coatGloss
     *
     * @param coatGloss the value for rabbit_info.coatGloss
     *
     * @mbg.generated
     */
    public void setCoatGloss(String coatGloss) {
        this.coatGloss = coatGloss == null ? null : coatGloss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.rabbitHouseNo
     *
     * @return the value of rabbit_info.rabbitHouseNo
     *
     * @mbg.generated
     */
    public String getRabbitHouseNo() {
        return rabbitHouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.rabbitHouseNo
     *
     * @param rabbitHouseNo the value for rabbit_info.rabbitHouseNo
     *
     * @mbg.generated
     */
    public void setRabbitHouseNo(String rabbitHouseNo) {
        this.rabbitHouseNo = rabbitHouseNo == null ? null : rabbitHouseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.identicalRabbits
     *
     * @return the value of rabbit_info.identicalRabbits
     *
     * @mbg.generated
     */
    public Integer getIdenticalRabbits() {
        return identicalRabbits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.identicalRabbits
     *
     * @param identicalRabbits the value for rabbit_info.identicalRabbits
     *
     * @mbg.generated
     */
    public void setIdenticalRabbits(Integer identicalRabbits) {
        this.identicalRabbits = identicalRabbits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.economiType
     *
     * @return the value of rabbit_info.economiType
     *
     * @mbg.generated
     */
    public String getEconomiType() {
        return economiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.economiType
     *
     * @param economiType the value for rabbit_info.economiType
     *
     * @mbg.generated
     */
    public void setEconomiType(String economiType) {
        this.economiType = economiType == null ? null : economiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.sex
     *
     * @return the value of rabbit_info.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.sex
     *
     * @param sex the value for rabbit_info.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.initialAge
     *
     * @return the value of rabbit_info.initialAge
     *
     * @mbg.generated
     */
    public String getInitialAge() {
        return initialAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.initialAge
     *
     * @param initialAge the value for rabbit_info.initialAge
     *
     * @mbg.generated
     */
    public void setInitialAge(String initialAge) {
        this.initialAge = initialAge == null ? null : initialAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.fineHairType
     *
     * @return the value of rabbit_info.fineHairType
     *
     * @mbg.generated
     */
    public String getFineHairType() {
        return fineHairType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.fineHairType
     *
     * @param fineHairType the value for rabbit_info.fineHairType
     *
     * @mbg.generated
     */
    public void setFineHairType(String fineHairType) {
        this.fineHairType = fineHairType == null ? null : fineHairType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.origin
     *
     * @return the value of rabbit_info.origin
     *
     * @mbg.generated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.origin
     *
     * @param origin the value for rabbit_info.origin
     *
     * @mbg.generated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.mainCoatColor
     *
     * @return the value of rabbit_info.mainCoatColor
     *
     * @mbg.generated
     */
    public String getMainCoatColor() {
        return mainCoatColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.mainCoatColor
     *
     * @param mainCoatColor the value for rabbit_info.mainCoatColor
     *
     * @mbg.generated
     */
    public void setMainCoatColor(String mainCoatColor) {
        this.mainCoatColor = mainCoatColor == null ? null : mainCoatColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.paternalNo
     *
     * @return the value of rabbit_info.paternalNo
     *
     * @mbg.generated
     */
    public String getPaternalNo() {
        return paternalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.paternalNo
     *
     * @param paternalNo the value for rabbit_info.paternalNo
     *
     * @mbg.generated
     */
    public void setPaternalNo(String paternalNo) {
        this.paternalNo = paternalNo == null ? null : paternalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.coatFeature
     *
     * @return the value of rabbit_info.coatFeature
     *
     * @mbg.generated
     */
    public String getCoatFeature() {
        return coatFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.coatFeature
     *
     * @param coatFeature the value for rabbit_info.coatFeature
     *
     * @mbg.generated
     */
    public void setCoatFeature(String coatFeature) {
        this.coatFeature = coatFeature == null ? null : coatFeature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.maternalNo
     *
     * @return the value of rabbit_info.maternalNo
     *
     * @mbg.generated
     */
    public String getMaternalNo() {
        return maternalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.maternalNo
     *
     * @param maternalNo the value for rabbit_info.maternalNo
     *
     * @mbg.generated
     */
    public void setMaternalNo(String maternalNo) {
        this.maternalNo = maternalNo == null ? null : maternalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.roughType
     *
     * @return the value of rabbit_info.roughType
     *
     * @mbg.generated
     */
    public String getRoughType() {
        return roughType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.roughType
     *
     * @param roughType the value for rabbit_info.roughType
     *
     * @mbg.generated
     */
    public void setRoughType(String roughType) {
        this.roughType = roughType == null ? null : roughType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.age
     *
     * @return the value of rabbit_info.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.age
     *
     * @param age the value for rabbit_info.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.coatColor
     *
     * @return the value of rabbit_info.coatColor
     *
     * @mbg.generated
     */
    public String getCoatColor() {
        return coatColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.coatColor
     *
     * @param coatColor the value for rabbit_info.coatColor
     *
     * @mbg.generated
     */
    public void setCoatColor(String coatColor) {
        this.coatColor = coatColor == null ? null : coatColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.bornDate
     *
     * @return the value of rabbit_info.bornDate
     *
     * @mbg.generated
     */
    public Date getBornDate() {
        return bornDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.bornDate
     *
     * @param bornDate the value for rabbit_info.bornDate
     *
     * @mbg.generated
     */
    public void setBornDate(Date bornDate) {
        this.bornDate = bornDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.nipplesNumber
     *
     * @return the value of rabbit_info.nipplesNumber
     *
     * @mbg.generated
     */
    public Integer getNipplesNumber() {
        return nipplesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.nipplesNumber
     *
     * @param nipplesNumber the value for rabbit_info.nipplesNumber
     *
     * @mbg.generated
     */
    public void setNipplesNumber(Integer nipplesNumber) {
        this.nipplesNumber = nipplesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rabbit_info.photo
     *
     * @return the value of rabbit_info.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rabbit_info.photo
     *
     * @param photo the value for rabbit_info.photo
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rabbitNo=").append(rabbitNo);
        sb.append(", cageNo=").append(cageNo);
        sb.append(", birthParity=").append(birthParity);
        sb.append(", initialWeight=").append(initialWeight);
        sb.append(", coatGloss=").append(coatGloss);
        sb.append(", rabbitHouseNo=").append(rabbitHouseNo);
        sb.append(", identicalRabbits=").append(identicalRabbits);
        sb.append(", economiType=").append(economiType);
        sb.append(", sex=").append(sex);
        sb.append(", initialAge=").append(initialAge);
        sb.append(", fineHairType=").append(fineHairType);
        sb.append(", origin=").append(origin);
        sb.append(", mainCoatColor=").append(mainCoatColor);
        sb.append(", paternalNo=").append(paternalNo);
        sb.append(", coatFeature=").append(coatFeature);
        sb.append(", maternalNo=").append(maternalNo);
        sb.append(", roughType=").append(roughType);
        sb.append(", age=").append(age);
        sb.append(", coatColor=").append(coatColor);
        sb.append(", bornDate=").append(bornDate);
        sb.append(", nipplesNumber=").append(nipplesNumber);
        sb.append(", photo=").append(photo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}