package com.nwafu.databaseoprations.entity;

import java.io.Serializable;

public class RebbitIllnessRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.rabbitNo
     *
     * @mbg.generated
     */
    private String rabbitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.illnessName
     *
     * @mbg.generated
     */
    private String illnessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.medicine
     *
     * @mbg.generated
     */
    private String medicine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.effect
     *
     * @mbg.generated
     */
    private String effect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.reuse
     *
     * @mbg.generated
     */
    private String reuse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.farm_Uuid
     *
     * @mbg.generated
     */
    private String farm_Uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.rabbitHouse
     *
     * @mbg.generated
     */
    private String rabbitHouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.cageNo
     *
     * @mbg.generated
     */
    private String cageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.uploadUser
     *
     * @mbg.generated
     */
    private String uploadUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebbit_illness_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebbit_illness_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.id
     *
     * @return the value of rebbit_illness_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.id
     *
     * @param id the value for rebbit_illness_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.rabbitNo
     *
     * @return the value of rebbit_illness_record.rabbitNo
     *
     * @mbg.generated
     */
    public String getRabbitNo() {
        return rabbitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.rabbitNo
     *
     * @param rabbitNo the value for rebbit_illness_record.rabbitNo
     *
     * @mbg.generated
     */
    public void setRabbitNo(String rabbitNo) {
        this.rabbitNo = rabbitNo == null ? null : rabbitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.illnessName
     *
     * @return the value of rebbit_illness_record.illnessName
     *
     * @mbg.generated
     */
    public String getIllnessName() {
        return illnessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.illnessName
     *
     * @param illnessName the value for rebbit_illness_record.illnessName
     *
     * @mbg.generated
     */
    public void setIllnessName(String illnessName) {
        this.illnessName = illnessName == null ? null : illnessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.medicine
     *
     * @return the value of rebbit_illness_record.medicine
     *
     * @mbg.generated
     */
    public String getMedicine() {
        return medicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.medicine
     *
     * @param medicine the value for rebbit_illness_record.medicine
     *
     * @mbg.generated
     */
    public void setMedicine(String medicine) {
        this.medicine = medicine == null ? null : medicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.effect
     *
     * @return the value of rebbit_illness_record.effect
     *
     * @mbg.generated
     */
    public String getEffect() {
        return effect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.effect
     *
     * @param effect the value for rebbit_illness_record.effect
     *
     * @mbg.generated
     */
    public void setEffect(String effect) {
        this.effect = effect == null ? null : effect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.reuse
     *
     * @return the value of rebbit_illness_record.reuse
     *
     * @mbg.generated
     */
    public String getReuse() {
        return reuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.reuse
     *
     * @param reuse the value for rebbit_illness_record.reuse
     *
     * @mbg.generated
     */
    public void setReuse(String reuse) {
        this.reuse = reuse == null ? null : reuse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.farm_Uuid
     *
     * @return the value of rebbit_illness_record.farm_Uuid
     *
     * @mbg.generated
     */
    public String getFarm_Uuid() {
        return farm_Uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.farm_Uuid
     *
     * @param farm_Uuid the value for rebbit_illness_record.farm_Uuid
     *
     * @mbg.generated
     */
    public void setFarm_Uuid(String farm_Uuid) {
        this.farm_Uuid = farm_Uuid == null ? null : farm_Uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.rabbitHouse
     *
     * @return the value of rebbit_illness_record.rabbitHouse
     *
     * @mbg.generated
     */
    public String getRabbitHouse() {
        return rabbitHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.rabbitHouse
     *
     * @param rabbitHouse the value for rebbit_illness_record.rabbitHouse
     *
     * @mbg.generated
     */
    public void setRabbitHouse(String rabbitHouse) {
        this.rabbitHouse = rabbitHouse == null ? null : rabbitHouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.cageNo
     *
     * @return the value of rebbit_illness_record.cageNo
     *
     * @mbg.generated
     */
    public String getCageNo() {
        return cageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.cageNo
     *
     * @param cageNo the value for rebbit_illness_record.cageNo
     *
     * @mbg.generated
     */
    public void setCageNo(String cageNo) {
        this.cageNo = cageNo == null ? null : cageNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.uploadUser
     *
     * @return the value of rebbit_illness_record.uploadUser
     *
     * @mbg.generated
     */
    public String getUploadUser() {
        return uploadUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.uploadUser
     *
     * @param uploadUser the value for rebbit_illness_record.uploadUser
     *
     * @mbg.generated
     */
    public void setUploadUser(String uploadUser) {
        this.uploadUser = uploadUser == null ? null : uploadUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebbit_illness_record.remark
     *
     * @return the value of rebbit_illness_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebbit_illness_record.remark
     *
     * @param remark the value for rebbit_illness_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebbit_illness_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rabbitNo=").append(rabbitNo);
        sb.append(", illnessName=").append(illnessName);
        sb.append(", medicine=").append(medicine);
        sb.append(", effect=").append(effect);
        sb.append(", reuse=").append(reuse);
        sb.append(", farm_Uuid=").append(farm_Uuid);
        sb.append(", rabbitHouse=").append(rabbitHouse);
        sb.append(", cageNo=").append(cageNo);
        sb.append(", uploadUser=").append(uploadUser);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}