server.port: 11234

eureka:
  client:
    serviceUrl:
      defaultZone: http://116.62.150.116:8888/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: database-oprations
          uri: http://localhost:8412
          order: 0
          predicates:
            - Path=/actions/**
          filters:
            - StripPrefix=1
        - id: account-login-management
          uri: http://localhost:8300
          order: 0
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1