spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456
server:
  port: 8888

eureka:
  instance:
    hostname: lqc.rabbitManagement.com

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

