package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.FarmInfomation;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface FarmInfomationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_infomation
     *
     * @mbg.generated
     */
    int insert(List<FarmInfomation> farmInfomationList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_infomation
     *
     * @mbg.generated
     */
    List<FarmInfomation> selectAll();

    List<FarmInfomation> selectByCondition(String condition, String value);

    int deleteById(List<String> uuid);
}