package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitBreeding;
import java.util.List;

public interface RabbitBreedingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_breeding
     *
     * @mbg.generated
     */
    int insert(RabbitBreeding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_breeding
     *
     * @mbg.generated
     */
    List<RabbitBreeding> selectAll();
}