package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitIngredients;
import java.util.List;

public interface RabbitIngredientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_ingredients
     *
     * @mbg.generated
     */
    int insert(RabbitIngredients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_ingredients
     *
     * @mbg.generated
     */
    List<RabbitIngredients> selectAll();
}