package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitDynamicInformation;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper

public interface RabbitDynamicInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_dynamic_information
     *
     * @mbg.generated
     */
    int insert(List<RabbitDynamicInformation> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_dynamic_information
     *
     * @mbg.generated
     */
    List<RabbitDynamicInformation> selectAll();

    List<RabbitDynamicInformation> selectInfoByNo(String rabbitNo);

    int deleteInfoByRabbitNo(List<String> rabbitNo);
}