package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitMaterialsRecord;
import java.util.List;

public interface RabbitMaterialsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_materials_record
     *
     * @mbg.generated
     */
    int insert(RabbitMaterialsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_materials_record
     *
     * @mbg.generated
     */
    List<RabbitMaterialsRecord> selectAll();
}