package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitHealth;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RabbitHealthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_health
     *
     * @mbg.generated
     */
    int insert(List<RabbitHealth> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_health
     *
     * @mbg.generated
     */
    List<RabbitHealth> selectAll();

    List<RabbitHealth> selectByCondition(String condition, String value);

    int deleteInfoById(List<String> id);
}