package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitIllness;
import com.nwafu.databaseoprations.entity.RabbitIllnessPO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RabbitIllnessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_illness
     *
     * @mbg.generated
     */
    int insert(List<RabbitIllnessPO> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_illness
     *
     * @mbg.generated
     */
    List<RabbitIllness> selectAll();

    List<RabbitIllness> selectInfoByName(String name);

    int deleteInfoById(List<String> id);

    List<RabbitIllness> getAllIllnessByCondition(String condition, String value);
}