package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitChangeRecord;
import java.util.List;

public interface RabbitChangeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_change_record
     *
     * @mbg.generated
     */
    int insert(RabbitChangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_change_record
     *
     * @mbg.generated
     */
    List<RabbitChangeRecord> selectAll();

    int getInRabbitCount(String rabbitHouseNo, String startDate, String endDate);

    int getOutRabbitCount(String rabbitHosueNo, String startDate, String endDate);
}