package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitMaterialsRecord;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RabbitMaterialsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_materials_record
     *
     * @mbg.generated
     */
    int insert(List<RabbitMaterialsRecord> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_materials_record
     *
     * @mbg.generated
     */
    List<RabbitMaterialsRecord> selectAll();

    List<RabbitMaterialsRecord> selectByFeedType(String feedType);

    int deleteRecordById(List<String> id);
}