package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitDynamicInformation;
import java.util.List;

public interface RabbitDynamicInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_dynamic_information
     *
     * @mbg.generated
     */
    int insert(RabbitDynamicInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_dynamic_information
     *
     * @mbg.generated
     */
    List<RabbitDynamicInformation> selectAll();
}