package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitInfo;
import java.util.List;

public interface RabbitInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_info
     *
     * @mbg.generated
     */
    int insert(RabbitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_info
     *
     * @mbg.generated
     */
    List<RabbitInfo> selectAll();
}