package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitIllnessRecord;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RabbitIllnessRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebbit_illness_record
     *
     * @mbg.generated
     */
    int insert(List<RabbitIllnessRecord> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebbit_illness_record
     *
     * @mbg.generated
     */
    List<RabbitIllnessRecord> selectAll();

    List<RabbitIllnessRecord> selectInfoByName(String name);

    List<RabbitIllnessRecord> selectInfoByCondition(String condition, String value);

    int deleteInfoById(List<String> id);
}