package com.nwafu.databaseoprations.dao;

import com.nwafu.databaseoprations.entity.RabbitHealth;
import java.util.List;

public interface RabbitHealthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_health
     *
     * @mbg.generated
     */
    int insert(RabbitHealth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rabbit_health
     *
     * @mbg.generated
     */
    List<RabbitHealth> selectAll();
}